package com.ankamagames.wakfu.client.ui.dialog;

import java.util.*;
import com.ankamagames.xulor2.core.*;
import com.ankamagames.xulor2.util.*;
import com.ankamagames.xulor2.decorator.*;
import com.ankamagames.framework.graphics.image.*;
import com.ankamagames.xulor2.component.*;
import com.ankamagames.xulor2.layout.*;
import com.ankamagames.xulor2.util.alignment.*;
import com.ankamagames.xulor2.appearance.*;

public class Test implements BasicElementFactory
{
    private Stack<ElementMap> elementMaps;
    private Environment env;
    
    public Test() {
        super();
        this.elementMaps = new Stack<ElementMap>();
    }
    
    @Override
    public BasicElement getElement(final Environment env, final ElementMap item) {
        this.env = env;
        this.elementMaps.push(item);
        final ElementMap elementMap = this.elementMaps.peek();
        final Container checkOut = Container.checkOut();
        checkOut.setElementMap(elementMap);
        checkOut.onAttributesInitialized();
        final StaticLayoutData element = new StaticLayoutData();
        element.onCheckOut();
        element.setElementMap(elementMap);
        element.setSize(new Dimension(500, -2));
        element.setAlign(Alignment17.CENTER);
        checkOut.addBasicElement(element);
        element.onAttributesInitialized();
        element.onChildrenAdded();
        final DecoratorAppearance appearance = checkOut.getAppearance();
        appearance.setElementMap(elementMap);
        checkOut.addBasicElement(appearance);
        appearance.onAttributesInitialized();
        final PlainBackground element2 = new PlainBackground();
        element2.onCheckOut();
        element2.setElementMap(elementMap);
        element2.setColor(new Color(1.0f, 1.0f, 1.0f, 1.0f));
        appearance.addBasicElement(element2);
        element2.onAttributesInitialized();
        element2.onChildrenAdded();
        appearance.onChildrenAdded();
        final TableLayout element3 = new TableLayout();
        element3.onCheckOut();
        element3.setColumns(3);
        element3.setRows(2);
        checkOut.addBasicElement(element3);
        element3.onAttributesInitialized();
        element3.onChildrenAdded();
        final Label element4 = new Label();
        element4.onCheckOut();
        element4.setElementMap(elementMap);
        element4.setText("text court");
        element4.setExpandable(false);
        checkOut.addBasicElement(element4);
        element4.onAttributesInitialized();
        final TableLayoutData element5 = new TableLayoutData();
        element5.onCheckOut();
        element5.setElementMap(elementMap);
        element5.setRow(0);
        element5.setColumn(0);
        element5.setHorizontalAlign(Alignment9.WEST);
        element4.addBasicElement(element5);
        element5.onAttributesInitialized();
        element5.onChildrenAdded();
        element4.onChildrenAdded();
        final Label element6 = new Label();
        element6.onCheckOut();
        element6.setElementMap(elementMap);
        element6.setPrefSize(new Dimension(50, 0));
        element6.setText("1");
        checkOut.addBasicElement(element6);
        element6.onAttributesInitialized();
        final DecoratorAppearance appearance2 = element6.getAppearance();
        appearance2.setElementMap(elementMap);
        ((TextWidgetAppearance)appearance2).setAlign(Alignment9.EAST);
        element6.addBasicElement(appearance2);
        appearance2.onAttributesInitialized();
        appearance2.onChildrenAdded();
        final TableLayoutData element7 = new TableLayoutData();
        element7.onCheckOut();
        element7.setElementMap(elementMap);
        element7.setRow(0);
        element7.setColumn(1);
        element7.setHorizontalAlign(Alignment9.EAST);
        element6.addBasicElement(element7);
        element7.onAttributesInitialized();
        element7.onChildrenAdded();
        element6.onChildrenAdded();
        final Label element8 = new Label();
        element8.onCheckOut();
        element8.setElementMap(elementMap);
        element8.setText("Longue Description de ouf ! Et m\u00eame plus !");
        checkOut.addBasicElement(element8);
        element8.onAttributesInitialized();
        final TableLayoutData element9 = new TableLayoutData();
        element9.onCheckOut();
        element9.setElementMap(elementMap);
        element9.setRow(0);
        element9.setColumn(2);
        element8.addBasicElement(element9);
        element9.onAttributesInitialized();
        element9.onChildrenAdded();
        element8.onChildrenAdded();
        final Label element10 = new Label();
        element10.onCheckOut();
        element10.setElementMap(elementMap);
        element10.setText("Beaucoup plus long !");
        element10.setExpandable(false);
        checkOut.addBasicElement(element10);
        element10.onAttributesInitialized();
        final TableLayoutData element11 = new TableLayoutData();
        element11.onCheckOut();
        element11.setElementMap(elementMap);
        element11.setRow(1);
        element11.setColumn(0);
        element11.setVerticalAlign(Alignment9.CENTER);
        element10.addBasicElement(element11);
        element11.onAttributesInitialized();
        element11.onChildrenAdded();
        element10.onChildrenAdded();
        final Label element12 = new Label();
        element12.onCheckOut();
        element12.setElementMap(elementMap);
        element12.setText("2");
        checkOut.addBasicElement(element12);
        element12.onAttributesInitialized();
        final TableLayoutData element13 = new TableLayoutData();
        element13.onCheckOut();
        element13.setElementMap(elementMap);
        element13.setRow(1);
        element13.setColumn(1);
        element13.setHorizontalAlign(Alignment9.EAST);
        element12.addBasicElement(element13);
        element13.onAttributesInitialized();
        element13.onChildrenAdded();
        element12.onChildrenAdded();
        final Label element14 = new Label();
        element14.onCheckOut();
        element14.setElementMap(elementMap);
        element14.setText("Description courte");
        checkOut.addBasicElement(element14);
        element14.onAttributesInitialized();
        final TableLayoutData element15 = new TableLayoutData();
        element15.onCheckOut();
        element15.setElementMap(elementMap);
        element15.setRow(1);
        element15.setColumn(2);
        element14.addBasicElement(element15);
        element15.onAttributesInitialized();
        element15.onChildrenAdded();
        element14.onChildrenAdded();
        checkOut.onChildrenAdded();
        return checkOut;
    }
}
