package com.ankamagames.xulor2.core.taglibrary;

import org.apache.log4j.*;
import com.ankamagames.xulor2.component.table.*;
import com.ankamagames.xulor2.component.colorpicker.*;
import com.ankamagames.xulor2.component.*;
import com.ankamagames.xulor2.layout.*;
import com.ankamagames.xulor2.appearance.*;
import com.ankamagames.xulor2.core.*;
import com.ankamagames.xulor2.appearance.spacing.*;
import com.ankamagames.xulor2.decorator.*;
import com.ankamagames.xulor2.core.form.*;
import com.ankamagames.xulor2.core.renderer.*;
import com.ankamagames.xulor2.property.*;
import com.ankamagames.xulor2.core.renderer.condition.*;
import com.ankamagames.xulor2.nongraphical.*;

public class XulorTagLibrary extends TagLibrary
{
    private static final Logger m_logger;
    private static final XulorTagLibrary m_instance;
    
    public static XulorTagLibrary getInstance() {
        return XulorTagLibrary.m_instance;
    }
    
    public void registerTags() {
        XulorTagLibrary.m_logger.info((Object)"[Xulor] Registering tags");
        this.registerTag("AnimatedElementViewer", AnimatedElementViewer.class);
        this.registerTag("animatedLoadingViewer", AnimatedLoadingViewer.class);
        this.registerTag("AnimatedImage", AnimatedImage.class);
        this.registerTag("basicColorPicker", BasicColorPicker.class);
        this.registerTag("Button", Button.class);
        this.registerTag("calendar", CalendarWidget.class);
        this.registerTag("rollingText", RollingText.class);
        this.registerTag("ComboBoxPlus", ComboBox.class);
        this.registerTag("ComboBox", ComboBox.class);
        this.registerTag("compass", CompassWidget.class);
        this.registerTag("Container", Container.class);
        this.registerTag("DisplayContainer", DisplayContainer.class);
        this.registerTag("dndc", DragNDropContainer.class);
        this.registerTag("drawer", Drawer.class);
        this.registerTag("FlippingImage", FlippingImage.class);
        this.registerTag("FoldingContainer", FoldingContainer.class);
        this.registerTag("graph", Graph.class);
        this.registerTag("Image", Image.class);
        this.registerTag("Label", Label.class);
        this.registerTag("LayeredContainer", LayeredContainer.class);
        this.registerTag("List", List.class);
        this.registerTag("MapNavigator", MapNavigator.class);
        this.registerTag("map", MapWidget.class);
        this.registerTag("multipleImage", MultipleImage.class);
        this.registerTag("PopupMenu", PopupMenu.class);
        this.registerTag("progressBar", ProgressBar.class);
        this.registerTag("progressText", ProgressText.class);
        this.registerTag("RadioButton", RadioButton.class);
        this.registerTag("renderableContainer", RenderableContainer.class);
        this.registerTag("RepeatableImage", RepeatableImage.class);
        this.registerTag("RootContainer", RootContainer.class);
        this.registerTag("RadioGroup", RadioGroup.class);
        this.registerTag("Separator", Separator.class);
        this.registerTag("Slider", Slider.class);
        this.registerTag("smiley", SmileyWidget.class);
        this.registerTag("ScrollBar", ScrollBar.class);
        this.registerTag("ScrollContainer", ScrollContainer.class);
        this.registerTag("StackList", StackList.class);
        this.registerTag("spacer", Spacer.class);
        this.registerTag("TabbedContainer", TabbedContainer.class);
        this.registerTag("TabItem", TabItem.class);
        this.registerTag("table", Table.class);
        this.registerTag("tableColumn", TableColumn.class);
        this.registerTag("TextEditor", TextEditor.class);
        this.registerTag("TextView", TextView.class);
        this.registerTag("tintIntensityColorPicker", TintIntensityColorPicker.class);
        this.registerTag("CheckBox", ToggleButton.class);
        this.registerTag("ToggleButton", ToggleButton.class);
        this.registerTag("tournament", Tournament.class);
        this.registerTag("tree", Tree.class);
        this.registerTag("MRU", UniversalRadialMenu.class);
        this.registerTag("valueSelector", ValueSelector.class);
        this.registerTag("Video", VideoWidget.class);
        this.registerTag("WatcherContainer", WatcherContainer.class);
        this.registerTag("wakfuBubble", WakfuBubbleWidget.class);
        this.registerTag("immutableWakfuBubble", ImmutableWakfuBubbleWidget.class);
        this.registerTag("Window", Window.class);
        this.registerTag("MessageBox", Window.class);
        this.registerTag("WindowMovePoint", WindowMovePoint.class);
        this.registerTag("WMP", WindowMovePoint.class);
        this.registerTag("WindowResizePoint", WindowResizePoint.class);
        this.registerTag("WRP", WindowResizePoint.class);
        this.registerTag("bl", BorderLayout.class);
        this.registerTag("BorderLayout", BorderLayout.class);
        this.registerTag("bld", BorderLayoutData.class);
        this.registerTag("borderLayoutData", BorderLayoutData.class);
        this.registerTag("gl", GlidingLayout.class);
        this.registerTag("gld", GlidingLayoutData.class);
        this.registerTag("rl", RowLayout.class);
        this.registerTag("RowLayout", RowLayout.class);
        this.registerTag("rld", RowLayoutData.class);
        this.registerTag("Spring", Spring.class);
        this.registerTag("SpringLayout", SpringLayout.class);
        this.registerTag("SPL", SpringLayout.class);
        this.registerTag("SpringLayoutData", SpringLayoutData.class);
        this.registerTag("spld", SpringLayoutData.class);
        this.registerTag("StaticLayout", StaticLayout.class);
        this.registerTag("sl", StaticLayout.class);
        this.registerTag("StaticLayoutData", StaticLayoutData.class);
        this.registerTag("sld", StaticLayoutData.class);
        this.registerTag("tl", TableLayout.class);
        this.registerTag("tld", TableLayoutData.class);
        this.registerTag("AnimatedElementViewerAppearance", AnimatedElementViewerAppearance.class);
        this.registerTag("ButtonAppearance", ButtonAppearance.class);
        this.registerTag("ComboBoxAppearance", ComboBoxAppearance.class);
        this.registerTag("Appearance", DecoratorAppearance.class);
        this.registerTag("PopupMenuAppearance", DecoratorAppearance.class);
        this.registerTag("ScrollBarAppearance", DecoratorAppearance.class);
        this.registerTag("ScrollContainerAppearance", DecoratorAppearance.class);
        this.registerTag("SliderAppearance", DecoratorAppearance.class);
        this.registerTag("WindowAppearance", DecoratorAppearance.class);
        this.registerTag("ImageAppearance", ImageAppearance.class);
        this.registerTag("mapAppearance", MapAppearance.class);
        this.registerTag("ListAppearance", ListAppearance.class);
        this.registerTag("progressBarAppearance", ProgressBarAppearance.class);
        this.registerTag("RadioButtonAppearance", RadioButtonAppearance.class);
        this.registerTag("TextWidgetAppearance", TextWidgetAppearance.class);
        this.registerTag("TextViewAppearance", TextWidgetAppearance.class);
        this.registerTag("TextEditorAppearance", TextWidgetAppearance.class);
        this.registerTag("LabelAppearance", TextWidgetAppearance.class);
        this.registerTag("ToggleButtonAppearance", ToggleButtonAppearance.class);
        this.registerTag("Color", ColorElement.class);
        this.registerTag("NamedColor", ColorElement.class);
        this.registerTag("Font", FontElement.class);
        this.registerTag("pixmap", PixmapElement.class);
        this.registerTag("Sound", SoundTrigger.class);
        this.registerTag("border", Border.class);
        this.registerTag("margin", Margin.class);
        this.registerTag("padding", Padding.class);
        this.registerTag("BubbleBorder", BubbleBorder.class);
        this.registerTag("GradientBackground", GradientBackground.class);
        this.registerTag("Particle", ParticleDecorator.class);
        this.registerTag("PixmapBackground", PixmapBackground.class);
        this.registerTag("PixmapBorder", PixmapBorder.class);
        this.registerTag("pixmapBorder16", PixmapBorder16.class);
        this.registerTag("PlainBackground", PlainBackground.class);
        this.registerTag("PlainBorder", PlainBorder.class);
        this.registerTag("SwitchingPlainBackground", SwitchingPlainBackground.class);
        this.registerTag("TiledPixmapBackground", TiledPixmapBackground.class);
        this.registerTag("data", Data.class);
        this.registerTag("Form", Form.class);
        this.registerTag("ItemRenderer", ItemRenderer.class);
        this.registerTag("Item", ItemElement.class);
        this.registerTag("Property", PropertyElement.class);
        this.registerTag("ItemCondition", ItemCondition.class);
        this.registerTag("ListCondition", ListCondition.class);
        this.registerTag("And", AndCondition.class);
        this.registerTag("Or", OrCondition.class);
        this.registerTag("Not", NotCondition.class);
        this.registerTag("Condition", ConditionResult.class);
        this.registerTag("isEqual", EqualCondition.class);
        this.registerTag("isGreater", GreaterCondition.class);
        this.registerTag("isLess", LessCondition.class);
        this.registerTag("isNull", NullCondition.class);
        this.registerTag("isNotNull", NotNullCondition.class);
        this.registerTag("isNotEqual", NotEqualCondition.class);
        this.registerTag("propertyExists", PropertyExistsCondition.class);
        this.registerTag("isTrue", TrueCondition.class);
        this.registerTag("isFalse", FalseCondition.class);
        this.registerTag("StringCondition", StringCondition.class);
        this.registerTag("CollectionCondition", CollectionCondition.class);
        this.registerTag("ValueReplacer", ValueReplacer.class);
        this.registerTag("BitwiseOperation", BitwiseOperation.class);
        this.registerTag("tooltip", ToolTipElement.class);
        this.registerTag("popup", PopupElement.class);
    }
    
    static {
        m_logger = Logger.getLogger((Class)XulorTagLibrary.class);
        m_instance = new XulorTagLibrary();
    }
}
