package com.ankamagames.wakfu.client.ui.theme;

import java.util.*;
import com.ankamagames.xulor2.component.*;
import com.ankamagames.xulor2.*;
import com.ankamagames.xulor2.core.*;
import com.ankamagames.framework.graphics.image.*;
import com.ankamagames.xulor2.util.alignment.*;
import com.ankamagames.xulor2.decorator.*;
import com.ankamagames.xulor2.appearance.*;

public class Button implements StyleSetter
{
    private DocumentParser doc;
    private Stack<ElementMap> elementMaps;
    
    public Button() {
        super();
        this.elementMaps = new Stack<ElementMap>();
    }
    
    @Override
    public void applyStyle(final ElementMap item, final DocumentParser doc, final Widget widget) {
        this.doc = doc;
        this.elementMaps.push(item);
        final ElementMap elementMap = this.elementMaps.peek();
        final DecoratorAppearance appearance = widget.getAppearance();
        appearance.setElementMap(elementMap);
        ((TextWidgetAppearance)appearance).setAlignment(Alignment9.CENTER);
        appearance.setState("default");
        widget.addBasicElement(appearance);
        appearance.onAttributesInitialized();
        final FontElement checkOut = FontElement.checkOut();
        checkOut.setRenderer(Xulor.getInstance().getDocumentParser().getFont("defaultBoldFont"));
        checkOut.setElementMap(elementMap);
        appearance.addBasicElement(checkOut);
        checkOut.onAttributesInitialized();
        checkOut.onChildrenAdded();
        final String id = "mecanicBlueColor";
        final ColorElement checkOut2 = ColorElement.checkOut();
        checkOut2.setElementMap(elementMap);
        if (elementMap != null && id != null) {
            elementMap.add(id, checkOut2);
        }
        checkOut2.setColor(new Color(0.32f, 0.39f, 0.42f, 1.0f));
        appearance.addBasicElement(checkOut2);
        checkOut2.onAttributesInitialized();
        checkOut2.onChildrenAdded();
        final String id2 = "buttonBackgroundDefault";
        final PixmapBackground checkOut3 = PixmapBackground.checkOut();
        checkOut3.setElementMap(elementMap);
        if (elementMap != null && id2 != null) {
            elementMap.add(id2, checkOut3);
        }
        checkOut3.setScaled(true);
        appearance.addBasicElement(checkOut3);
        checkOut3.onAttributesInitialized();
        final PixmapElement checkOut4 = PixmapElement.checkOut();
        checkOut4.setElementMap(elementMap);
        checkOut4.setHeight(14);
        checkOut4.setPosition(Alignment17.CENTER);
        checkOut4.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut4.setWidth(20);
        checkOut4.setX(224);
        checkOut4.setY(181);
        checkOut3.addBasicElement(checkOut4);
        checkOut4.onAttributesInitialized();
        checkOut4.onChildrenAdded();
        checkOut3.onChildrenAdded();
        final String id3 = "buttonBorderDefault";
        final PixmapBorder pixmapBorder = new PixmapBorder();
        pixmapBorder.onCheckOut();
        pixmapBorder.setElementMap(elementMap);
        if (elementMap != null && id3 != null) {
            elementMap.add(id3, pixmapBorder);
        }
        appearance.addBasicElement(pixmapBorder);
        pixmapBorder.onAttributesInitialized();
        final PixmapElement checkOut5 = PixmapElement.checkOut();
        checkOut5.setElementMap(elementMap);
        checkOut5.setHeight(4);
        checkOut5.setPosition(Alignment17.NORTH_WEST);
        checkOut5.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut5.setWidth(4);
        checkOut5.setX(863);
        checkOut5.setY(254);
        pixmapBorder.addBasicElement(checkOut5);
        checkOut5.onAttributesInitialized();
        checkOut5.onChildrenAdded();
        final PixmapElement checkOut6 = PixmapElement.checkOut();
        checkOut6.setElementMap(elementMap);
        checkOut6.setHeight(4);
        checkOut6.setPosition(Alignment17.NORTH);
        checkOut6.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut6.setWidth(20);
        checkOut6.setX(959);
        checkOut6.setY(134);
        pixmapBorder.addBasicElement(checkOut6);
        checkOut6.onAttributesInitialized();
        checkOut6.onChildrenAdded();
        final PixmapElement checkOut7 = PixmapElement.checkOut();
        checkOut7.setElementMap(elementMap);
        checkOut7.setHeight(4);
        checkOut7.setPosition(Alignment17.NORTH_EAST);
        checkOut7.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut7.setWidth(5);
        checkOut7.setX(681);
        checkOut7.setY(283);
        pixmapBorder.addBasicElement(checkOut7);
        checkOut7.onAttributesInitialized();
        checkOut7.onChildrenAdded();
        final PixmapElement checkOut8 = PixmapElement.checkOut();
        checkOut8.setElementMap(elementMap);
        checkOut8.setHeight(14);
        checkOut8.setPosition(Alignment17.EAST);
        checkOut8.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut8.setWidth(5);
        checkOut8.setX(820);
        checkOut8.setY(851);
        pixmapBorder.addBasicElement(checkOut8);
        checkOut8.onAttributesInitialized();
        checkOut8.onChildrenAdded();
        final PixmapElement checkOut9 = PixmapElement.checkOut();
        checkOut9.setElementMap(elementMap);
        checkOut9.setHeight(5);
        checkOut9.setPosition(Alignment17.SOUTH_EAST);
        checkOut9.setTexture(this.doc.getTexture("default_0.tga"));
        checkOut9.setWidth(5);
        checkOut9.setX(690);
        checkOut9.setY(374);
        pixmapBorder.addBasicElement(checkOut9);
        checkOut9.onAttributesInitialized();
        checkOut9.onChildrenAdded();
        final PixmapElement checkOut10 = PixmapElement.checkOut();
        checkOut10.setElementMap(elementMap);
        checkOut10.setHeight(5);
        checkOut10.setPosition(Alignment17.SOUTH);
        checkOut10.setTexture(this.doc.getTexture("default_0.tga"));
        checkOut10.setWidth(20);
        checkOut10.setX(796);
        checkOut10.setY(411);
        pixmapBorder.addBasicElement(checkOut10);
        checkOut10.onAttributesInitialized();
        checkOut10.onChildrenAdded();
        final PixmapElement checkOut11 = PixmapElement.checkOut();
        checkOut11.setElementMap(elementMap);
        checkOut11.setHeight(5);
        checkOut11.setPosition(Alignment17.SOUTH_WEST);
        checkOut11.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut11.setWidth(4);
        checkOut11.setX(228);
        checkOut11.setY(332);
        pixmapBorder.addBasicElement(checkOut11);
        checkOut11.onAttributesInitialized();
        checkOut11.onChildrenAdded();
        final PixmapElement checkOut12 = PixmapElement.checkOut();
        checkOut12.setElementMap(elementMap);
        checkOut12.setHeight(14);
        checkOut12.setPosition(Alignment17.WEST);
        checkOut12.setTexture(this.doc.getTexture("default_0.tga"));
        checkOut12.setWidth(4);
        checkOut12.setX(828);
        checkOut12.setY(59);
        pixmapBorder.addBasicElement(checkOut12);
        checkOut12.onAttributesInitialized();
        checkOut12.onChildrenAdded();
        pixmapBorder.onChildrenAdded();
        appearance.onChildrenAdded();
        final DecoratorAppearance appearance2 = widget.getAppearance();
        appearance2.setElementMap(elementMap);
        ((TextWidgetAppearance)appearance2).setAlignment(Alignment9.CENTER);
        appearance2.setState("mouseHover");
        widget.addBasicElement(appearance2);
        appearance2.onAttributesInitialized();
        final String id4 = "mecanicBlueColor";
        final ColorElement checkOut13 = ColorElement.checkOut();
        checkOut13.setElementMap(elementMap);
        if (elementMap != null && id4 != null) {
            elementMap.add(id4, checkOut13);
        }
        checkOut13.setColor(new Color(0.32f, 0.39f, 0.42f, 1.0f));
        appearance2.addBasicElement(checkOut13);
        checkOut13.onAttributesInitialized();
        checkOut13.onChildrenAdded();
        final String id5 = "buttonBackgroundOver";
        final PixmapBackground checkOut14 = PixmapBackground.checkOut();
        checkOut14.setElementMap(elementMap);
        if (elementMap != null && id5 != null) {
            elementMap.add(id5, checkOut14);
        }
        checkOut14.setEnabled(false);
        checkOut14.setScaled(true);
        appearance2.addBasicElement(checkOut14);
        checkOut14.onAttributesInitialized();
        final PixmapElement checkOut15 = PixmapElement.checkOut();
        checkOut15.setElementMap(elementMap);
        checkOut15.setHeight(14);
        checkOut15.setPosition(Alignment17.CENTER);
        checkOut15.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut15.setWidth(20);
        checkOut15.setX(392);
        checkOut15.setY(182);
        checkOut14.addBasicElement(checkOut15);
        checkOut15.onAttributesInitialized();
        checkOut15.onChildrenAdded();
        checkOut14.onChildrenAdded();
        final String id6 = "buttonBorderOver";
        final PixmapBorder pixmapBorder2 = new PixmapBorder();
        pixmapBorder2.onCheckOut();
        pixmapBorder2.setElementMap(elementMap);
        if (elementMap != null && id6 != null) {
            elementMap.add(id6, pixmapBorder2);
        }
        pixmapBorder2.setEnabled(false);
        appearance2.addBasicElement(pixmapBorder2);
        pixmapBorder2.onAttributesInitialized();
        final PixmapElement checkOut16 = PixmapElement.checkOut();
        checkOut16.setElementMap(elementMap);
        checkOut16.setHeight(4);
        checkOut16.setPosition(Alignment17.NORTH_WEST);
        checkOut16.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut16.setWidth(4);
        checkOut16.setX(592);
        checkOut16.setY(255);
        pixmapBorder2.addBasicElement(checkOut16);
        checkOut16.onAttributesInitialized();
        checkOut16.onChildrenAdded();
        final PixmapElement checkOut17 = PixmapElement.checkOut();
        checkOut17.setElementMap(elementMap);
        checkOut17.setHeight(4);
        checkOut17.setPosition(Alignment17.NORTH);
        checkOut17.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut17.setWidth(20);
        checkOut17.setX(704);
        checkOut17.setY(134);
        pixmapBorder2.addBasicElement(checkOut17);
        checkOut17.onAttributesInitialized();
        checkOut17.onChildrenAdded();
        final PixmapElement checkOut18 = PixmapElement.checkOut();
        checkOut18.setElementMap(elementMap);
        checkOut18.setHeight(4);
        checkOut18.setPosition(Alignment17.NORTH_EAST);
        checkOut18.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut18.setWidth(5);
        checkOut18.setX(55);
        checkOut18.setY(221);
        pixmapBorder2.addBasicElement(checkOut18);
        checkOut18.onAttributesInitialized();
        checkOut18.onChildrenAdded();
        final PixmapElement checkOut19 = PixmapElement.checkOut();
        checkOut19.setElementMap(elementMap);
        checkOut19.setHeight(14);
        checkOut19.setPosition(Alignment17.EAST);
        checkOut19.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut19.setWidth(5);
        checkOut19.setX(927);
        checkOut19.setY(632);
        pixmapBorder2.addBasicElement(checkOut19);
        checkOut19.onAttributesInitialized();
        checkOut19.onChildrenAdded();
        final PixmapElement checkOut20 = PixmapElement.checkOut();
        checkOut20.setElementMap(elementMap);
        checkOut20.setHeight(5);
        checkOut20.setPosition(Alignment17.SOUTH_EAST);
        checkOut20.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut20.setWidth(5);
        checkOut20.setX(936);
        checkOut20.setY(244);
        pixmapBorder2.addBasicElement(checkOut20);
        checkOut20.onAttributesInitialized();
        checkOut20.onChildrenAdded();
        final PixmapElement checkOut21 = PixmapElement.checkOut();
        checkOut21.setElementMap(elementMap);
        checkOut21.setHeight(5);
        checkOut21.setPosition(Alignment17.SOUTH);
        checkOut21.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut21.setWidth(20);
        checkOut21.setX(366);
        checkOut21.setY(142);
        pixmapBorder2.addBasicElement(checkOut21);
        checkOut21.onAttributesInitialized();
        checkOut21.onChildrenAdded();
        final PixmapElement checkOut22 = PixmapElement.checkOut();
        checkOut22.setElementMap(elementMap);
        checkOut22.setHeight(5);
        checkOut22.setPosition(Alignment17.SOUTH_WEST);
        checkOut22.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut22.setWidth(4);
        checkOut22.setX(228);
        checkOut22.setY(348);
        pixmapBorder2.addBasicElement(checkOut22);
        checkOut22.onAttributesInitialized();
        checkOut22.onChildrenAdded();
        final PixmapElement checkOut23 = PixmapElement.checkOut();
        checkOut23.setElementMap(elementMap);
        checkOut23.setHeight(14);
        checkOut23.setPosition(Alignment17.WEST);
        checkOut23.setTexture(this.doc.getTexture("default_0.tga"));
        checkOut23.setWidth(4);
        checkOut23.setX(1017);
        checkOut23.setY(106);
        pixmapBorder2.addBasicElement(checkOut23);
        checkOut23.onAttributesInitialized();
        checkOut23.onChildrenAdded();
        pixmapBorder2.onChildrenAdded();
        appearance2.onChildrenAdded();
        final DecoratorAppearance appearance3 = widget.getAppearance();
        appearance3.setElementMap(elementMap);
        ((TextWidgetAppearance)appearance3).setAlignment(Alignment9.CENTER);
        appearance3.setState("pressed");
        widget.addBasicElement(appearance3);
        appearance3.onAttributesInitialized();
        final String id7 = "mecanicBlueColor";
        final ColorElement checkOut24 = ColorElement.checkOut();
        checkOut24.setElementMap(elementMap);
        if (elementMap != null && id7 != null) {
            elementMap.add(id7, checkOut24);
        }
        checkOut24.setColor(new Color(0.32f, 0.39f, 0.42f, 1.0f));
        appearance3.addBasicElement(checkOut24);
        checkOut24.onAttributesInitialized();
        checkOut24.onChildrenAdded();
        final String id8 = "buttonBackgroundPressed";
        final PixmapBackground checkOut25 = PixmapBackground.checkOut();
        checkOut25.setElementMap(elementMap);
        if (elementMap != null && id8 != null) {
            elementMap.add(id8, checkOut25);
        }
        checkOut25.setEnabled(false);
        checkOut25.setScaled(true);
        appearance3.addBasicElement(checkOut25);
        checkOut25.onAttributesInitialized();
        final PixmapElement checkOut26 = PixmapElement.checkOut();
        checkOut26.setElementMap(elementMap);
        checkOut26.setHeight(14);
        checkOut26.setPosition(Alignment17.CENTER);
        checkOut26.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut26.setWidth(20);
        checkOut26.setX(876);
        checkOut26.setY(165);
        checkOut25.addBasicElement(checkOut26);
        checkOut26.onAttributesInitialized();
        checkOut26.onChildrenAdded();
        checkOut25.onChildrenAdded();
        final String id9 = "buttonBorderPressed";
        final PixmapBorder pixmapBorder3 = new PixmapBorder();
        pixmapBorder3.onCheckOut();
        pixmapBorder3.setElementMap(elementMap);
        if (elementMap != null && id9 != null) {
            elementMap.add(id9, pixmapBorder3);
        }
        pixmapBorder3.setEnabled(false);
        appearance3.addBasicElement(pixmapBorder3);
        pixmapBorder3.onAttributesInitialized();
        final PixmapElement checkOut27 = PixmapElement.checkOut();
        checkOut27.setElementMap(elementMap);
        checkOut27.setHeight(4);
        checkOut27.setPosition(Alignment17.NORTH_WEST);
        checkOut27.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut27.setWidth(4);
        checkOut27.setX(592);
        checkOut27.setY(269);
        pixmapBorder3.addBasicElement(checkOut27);
        checkOut27.onAttributesInitialized();
        checkOut27.onChildrenAdded();
        final PixmapElement checkOut28 = PixmapElement.checkOut();
        checkOut28.setElementMap(elementMap);
        checkOut28.setHeight(4);
        checkOut28.setPosition(Alignment17.NORTH);
        checkOut28.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut28.setWidth(20);
        checkOut28.setX(28);
        checkOut28.setY(134);
        pixmapBorder3.addBasicElement(checkOut28);
        checkOut28.onAttributesInitialized();
        checkOut28.onChildrenAdded();
        final PixmapElement checkOut29 = PixmapElement.checkOut();
        checkOut29.setElementMap(elementMap);
        checkOut29.setHeight(4);
        checkOut29.setPosition(Alignment17.NORTH_EAST);
        checkOut29.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut29.setWidth(5);
        checkOut29.setX(107);
        checkOut29.setY(212);
        pixmapBorder3.addBasicElement(checkOut29);
        checkOut29.onAttributesInitialized();
        checkOut29.onChildrenAdded();
        final PixmapElement checkOut30 = PixmapElement.checkOut();
        checkOut30.setElementMap(elementMap);
        checkOut30.setHeight(14);
        checkOut30.setPosition(Alignment17.EAST);
        checkOut30.setTexture(this.doc.getTexture("default_0.tga"));
        checkOut30.setWidth(5);
        checkOut30.setX(823);
        checkOut30.setY(105);
        pixmapBorder3.addBasicElement(checkOut30);
        checkOut30.onAttributesInitialized();
        checkOut30.onChildrenAdded();
        final PixmapElement checkOut31 = PixmapElement.checkOut();
        checkOut31.setElementMap(elementMap);
        checkOut31.setHeight(5);
        checkOut31.setPosition(Alignment17.SOUTH_EAST);
        checkOut31.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut31.setWidth(5);
        checkOut31.setX(215);
        checkOut31.setY(223);
        pixmapBorder3.addBasicElement(checkOut31);
        checkOut31.onAttributesInitialized();
        checkOut31.onChildrenAdded();
        final PixmapElement checkOut32 = PixmapElement.checkOut();
        checkOut32.setElementMap(elementMap);
        checkOut32.setHeight(5);
        checkOut32.setPosition(Alignment17.SOUTH);
        checkOut32.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut32.setWidth(20);
        checkOut32.setX(958);
        checkOut32.setY(514);
        pixmapBorder3.addBasicElement(checkOut32);
        checkOut32.onAttributesInitialized();
        checkOut32.onChildrenAdded();
        final PixmapElement checkOut33 = PixmapElement.checkOut();
        checkOut33.setElementMap(elementMap);
        checkOut33.setHeight(5);
        checkOut33.setPosition(Alignment17.SOUTH_WEST);
        checkOut33.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut33.setWidth(4);
        checkOut33.setX(228);
        checkOut33.setY(340);
        pixmapBorder3.addBasicElement(checkOut33);
        checkOut33.onAttributesInitialized();
        checkOut33.onChildrenAdded();
        final PixmapElement checkOut34 = PixmapElement.checkOut();
        checkOut34.setElementMap(elementMap);
        checkOut34.setHeight(14);
        checkOut34.setPosition(Alignment17.WEST);
        checkOut34.setTexture(this.doc.getTexture("default_0.tga"));
        checkOut34.setWidth(4);
        checkOut34.setX(828);
        checkOut34.setY(76);
        pixmapBorder3.addBasicElement(checkOut34);
        checkOut34.onAttributesInitialized();
        checkOut34.onChildrenAdded();
        pixmapBorder3.onChildrenAdded();
        appearance3.onChildrenAdded();
        final DecoratorAppearance appearance4 = widget.getAppearance();
        appearance4.setElementMap(elementMap);
        ((TextWidgetAppearance)appearance4).setAlignment(Alignment9.CENTER);
        appearance4.setState("disabled");
        widget.addBasicElement(appearance4);
        appearance4.onAttributesInitialized();
        final ColorElement checkOut35 = ColorElement.checkOut();
        checkOut35.setElementMap(elementMap);
        checkOut35.setColor(new Color(0.6f, 0.6f, 0.6f, 1.0f));
        appearance4.addBasicElement(checkOut35);
        checkOut35.onAttributesInitialized();
        checkOut35.onChildrenAdded();
        final String id10 = "buttonBackgroundDisabled";
        final PixmapBackground checkOut36 = PixmapBackground.checkOut();
        checkOut36.setElementMap(elementMap);
        if (elementMap != null && id10 != null) {
            elementMap.add(id10, checkOut36);
        }
        checkOut36.setEnabled(false);
        checkOut36.setScaled(true);
        appearance4.addBasicElement(checkOut36);
        checkOut36.onAttributesInitialized();
        final PixmapElement checkOut37 = PixmapElement.checkOut();
        checkOut37.setElementMap(elementMap);
        checkOut37.setHeight(14);
        checkOut37.setPosition(Alignment17.CENTER);
        checkOut37.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut37.setWidth(20);
        checkOut37.setX(876);
        checkOut37.setY(182);
        checkOut36.addBasicElement(checkOut37);
        checkOut37.onAttributesInitialized();
        checkOut37.onChildrenAdded();
        checkOut36.onChildrenAdded();
        final String id11 = "buttonBorderDisabled";
        final PixmapBorder pixmapBorder4 = new PixmapBorder();
        pixmapBorder4.onCheckOut();
        pixmapBorder4.setElementMap(elementMap);
        if (elementMap != null && id11 != null) {
            elementMap.add(id11, pixmapBorder4);
        }
        pixmapBorder4.setEnabled(false);
        appearance4.addBasicElement(pixmapBorder4);
        pixmapBorder4.onAttributesInitialized();
        final PixmapElement checkOut38 = PixmapElement.checkOut();
        checkOut38.setElementMap(elementMap);
        checkOut38.setHeight(4);
        checkOut38.setPosition(Alignment17.NORTH_WEST);
        checkOut38.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut38.setWidth(4);
        checkOut38.setX(834);
        checkOut38.setY(197);
        pixmapBorder4.addBasicElement(checkOut38);
        checkOut38.onAttributesInitialized();
        checkOut38.onChildrenAdded();
        final PixmapElement checkOut39 = PixmapElement.checkOut();
        checkOut39.setElementMap(elementMap);
        checkOut39.setHeight(4);
        checkOut39.setPosition(Alignment17.NORTH);
        checkOut39.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut39.setWidth(20);
        checkOut39.setX(930);
        checkOut39.setY(134);
        pixmapBorder4.addBasicElement(checkOut39);
        checkOut39.onAttributesInitialized();
        checkOut39.onChildrenAdded();
        final PixmapElement checkOut40 = PixmapElement.checkOut();
        checkOut40.setElementMap(elementMap);
        checkOut40.setHeight(4);
        checkOut40.setPosition(Alignment17.NORTH_EAST);
        checkOut40.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut40.setWidth(5);
        checkOut40.setX(215);
        checkOut40.setY(216);
        pixmapBorder4.addBasicElement(checkOut40);
        checkOut40.onAttributesInitialized();
        checkOut40.onChildrenAdded();
        final PixmapElement checkOut41 = PixmapElement.checkOut();
        checkOut41.setElementMap(elementMap);
        checkOut41.setHeight(14);
        checkOut41.setPosition(Alignment17.EAST);
        checkOut41.setTexture(this.doc.getTexture("default_0.tga"));
        checkOut41.setWidth(5);
        checkOut41.setX(221);
        checkOut41.setY(16);
        pixmapBorder4.addBasicElement(checkOut41);
        checkOut41.onAttributesInitialized();
        checkOut41.onChildrenAdded();
        this.method0(pixmapBorder4);
        this.method1(pixmapBorder4);
        this.method2(pixmapBorder4);
        this.method3(pixmapBorder4);
        pixmapBorder4.onChildrenAdded();
        appearance4.onChildrenAdded();
    }
    
    public BasicElement method0(final BasicElement basicElement) {
        final ElementMap elementMap = this.elementMaps.peek();
        final PixmapElement checkOut = PixmapElement.checkOut();
        checkOut.setElementMap(elementMap);
        checkOut.setHeight(5);
        checkOut.setPosition(Alignment17.SOUTH_EAST);
        checkOut.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut.setWidth(5);
        checkOut.setX(24);
        checkOut.setY(244);
        basicElement.addBasicElement(checkOut);
        checkOut.onAttributesInitialized();
        checkOut.onChildrenAdded();
        return checkOut;
    }
    
    public BasicElement method1(final BasicElement basicElement) {
        final ElementMap elementMap = this.elementMaps.peek();
        final PixmapElement checkOut = PixmapElement.checkOut();
        checkOut.setElementMap(elementMap);
        checkOut.setHeight(5);
        checkOut.setPosition(Alignment17.SOUTH);
        checkOut.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut.setWidth(20);
        checkOut.setX(343);
        checkOut.setY(142);
        basicElement.addBasicElement(checkOut);
        checkOut.onAttributesInitialized();
        checkOut.onChildrenAdded();
        return checkOut;
    }
    
    public BasicElement method2(final BasicElement basicElement) {
        final ElementMap elementMap = this.elementMaps.peek();
        final PixmapElement checkOut = PixmapElement.checkOut();
        checkOut.setElementMap(elementMap);
        checkOut.setHeight(5);
        checkOut.setPosition(Alignment17.SOUTH_WEST);
        checkOut.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut.setWidth(4);
        checkOut.setX(538);
        checkOut.setY(268);
        basicElement.addBasicElement(checkOut);
        checkOut.onAttributesInitialized();
        checkOut.onChildrenAdded();
        return checkOut;
    }
    
    public BasicElement method3(final BasicElement basicElement) {
        final ElementMap elementMap = this.elementMaps.peek();
        final PixmapElement checkOut = PixmapElement.checkOut();
        checkOut.setElementMap(elementMap);
        checkOut.setHeight(14);
        checkOut.setPosition(Alignment17.WEST);
        checkOut.setTexture(this.doc.getTexture("default_0.tga"));
        checkOut.setWidth(4);
        checkOut.setX(828);
        checkOut.setY(42);
        basicElement.addBasicElement(checkOut);
        checkOut.onAttributesInitialized();
        checkOut.onChildrenAdded();
        return checkOut;
    }
}
