package com.ankamagames.wakfu.client.ui.theme;

import java.util.*;
import com.ankamagames.xulor2.component.*;
import com.ankamagames.xulor2.*;
import com.ankamagames.xulor2.core.*;
import com.ankamagames.framework.graphics.image.*;
import com.ankamagames.xulor2.util.alignment.*;
import com.ankamagames.xulor2.decorator.*;
import com.ankamagames.xulor2.appearance.*;

public class RadioButtonLogin implements StyleSetter
{
    private DocumentParser doc;
    private Stack<ElementMap> elementMaps;
    
    public RadioButtonLogin() {
        super();
        this.elementMaps = new Stack<ElementMap>();
    }
    
    @Override
    public void applyStyle(final ElementMap item, final DocumentParser doc, final Widget widget) {
        this.doc = doc;
        this.elementMaps.push(item);
        final ElementMap elementMap = this.elementMaps.peek();
        final DecoratorAppearance appearance = widget.getAppearance();
        appearance.setElementMap(elementMap);
        ((TextWidgetAppearance)appearance).setAlignment(Alignment9.CENTER);
        appearance.setState("default");
        widget.addBasicElement(appearance);
        appearance.onAttributesInitialized();
        final FontElement checkOut = FontElement.checkOut();
        checkOut.setRenderer(Xulor.getInstance().getDocumentParser().getFont("styledLightFont"));
        checkOut.setElementMap(elementMap);
        appearance.addBasicElement(checkOut);
        checkOut.onAttributesInitialized();
        checkOut.onChildrenAdded();
        final String id = "defaultDarkColor";
        final ColorElement checkOut2 = ColorElement.checkOut();
        checkOut2.setElementMap(elementMap);
        if (elementMap != null && id != null) {
            elementMap.add(id, checkOut2);
        }
        checkOut2.setColor(new Color(0.29f, 0.17f, 0.07f, 1.0f));
        appearance.addBasicElement(checkOut2);
        checkOut2.onAttributesInitialized();
        checkOut2.onChildrenAdded();
        final String id2 = "radioButtonBackgroundDefault";
        final PixmapBackground checkOut3 = PixmapBackground.checkOut();
        checkOut3.setElementMap(elementMap);
        if (elementMap != null && id2 != null) {
            elementMap.add(id2, checkOut3);
        }
        checkOut3.setScaled(true);
        appearance.addBasicElement(checkOut3);
        checkOut3.onAttributesInitialized();
        final PixmapElement checkOut4 = PixmapElement.checkOut();
        checkOut4.setElementMap(elementMap);
        checkOut4.setHeight(11);
        checkOut4.setPosition(Alignment17.CENTER);
        checkOut4.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut4.setWidth(16);
        checkOut4.setX(213);
        checkOut4.setY(103);
        checkOut3.addBasicElement(checkOut4);
        checkOut4.onAttributesInitialized();
        checkOut4.onChildrenAdded();
        checkOut3.onChildrenAdded();
        final String id3 = "radioButtonBorderDefault";
        final PixmapBorder pixmapBorder = new PixmapBorder();
        pixmapBorder.onCheckOut();
        pixmapBorder.setElementMap(elementMap);
        if (elementMap != null && id3 != null) {
            elementMap.add(id3, pixmapBorder);
        }
        appearance.addBasicElement(pixmapBorder);
        pixmapBorder.onAttributesInitialized();
        final PixmapElement checkOut5 = PixmapElement.checkOut();
        checkOut5.setElementMap(elementMap);
        checkOut5.setHeight(3);
        checkOut5.setPosition(Alignment17.NORTH_WEST);
        checkOut5.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut5.setWidth(3);
        checkOut5.setX(1014);
        checkOut5.setY(902);
        pixmapBorder.addBasicElement(checkOut5);
        checkOut5.onAttributesInitialized();
        checkOut5.onChildrenAdded();
        final PixmapElement checkOut6 = PixmapElement.checkOut();
        checkOut6.setElementMap(elementMap);
        checkOut6.setHeight(3);
        checkOut6.setPosition(Alignment17.NORTH);
        checkOut6.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut6.setWidth(16);
        checkOut6.setX(978);
        checkOut6.setY(232);
        pixmapBorder.addBasicElement(checkOut6);
        checkOut6.onAttributesInitialized();
        checkOut6.onChildrenAdded();
        final PixmapElement checkOut7 = PixmapElement.checkOut();
        checkOut7.setElementMap(elementMap);
        checkOut7.setHeight(3);
        checkOut7.setPosition(Alignment17.NORTH_EAST);
        checkOut7.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut7.setWidth(3);
        checkOut7.setX(974);
        checkOut7.setY(897);
        pixmapBorder.addBasicElement(checkOut7);
        checkOut7.onAttributesInitialized();
        checkOut7.onChildrenAdded();
        final PixmapElement checkOut8 = PixmapElement.checkOut();
        checkOut8.setElementMap(elementMap);
        checkOut8.setHeight(11);
        checkOut8.setPosition(Alignment17.EAST);
        checkOut8.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut8.setWidth(3);
        checkOut8.setX(1012);
        checkOut8.setY(987);
        pixmapBorder.addBasicElement(checkOut8);
        checkOut8.onAttributesInitialized();
        checkOut8.onChildrenAdded();
        final PixmapElement checkOut9 = PixmapElement.checkOut();
        checkOut9.setElementMap(elementMap);
        checkOut9.setHeight(3);
        checkOut9.setPosition(Alignment17.SOUTH_EAST);
        checkOut9.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut9.setWidth(3);
        checkOut9.setX(1009);
        checkOut9.setY(755);
        pixmapBorder.addBasicElement(checkOut9);
        checkOut9.onAttributesInitialized();
        checkOut9.onChildrenAdded();
        final PixmapElement checkOut10 = PixmapElement.checkOut();
        checkOut10.setElementMap(elementMap);
        checkOut10.setHeight(3);
        checkOut10.setPosition(Alignment17.SOUTH);
        checkOut10.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut10.setWidth(16);
        checkOut10.setX(924);
        checkOut10.setY(236);
        pixmapBorder.addBasicElement(checkOut10);
        checkOut10.onAttributesInitialized();
        checkOut10.onChildrenAdded();
        final PixmapElement checkOut11 = PixmapElement.checkOut();
        checkOut11.setElementMap(elementMap);
        checkOut11.setHeight(3);
        checkOut11.setPosition(Alignment17.SOUTH_WEST);
        checkOut11.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut11.setWidth(3);
        checkOut11.setX(1014);
        checkOut11.setY(908);
        pixmapBorder.addBasicElement(checkOut11);
        checkOut11.onAttributesInitialized();
        checkOut11.onChildrenAdded();
        final PixmapElement checkOut12 = PixmapElement.checkOut();
        checkOut12.setElementMap(elementMap);
        checkOut12.setHeight(11);
        checkOut12.setPosition(Alignment17.WEST);
        checkOut12.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut12.setWidth(3);
        checkOut12.setX(1012);
        checkOut12.setY(973);
        pixmapBorder.addBasicElement(checkOut12);
        checkOut12.onAttributesInitialized();
        checkOut12.onChildrenAdded();
        pixmapBorder.onChildrenAdded();
        appearance.onChildrenAdded();
        final DecoratorAppearance appearance2 = widget.getAppearance();
        appearance2.setElementMap(elementMap);
        ((TextWidgetAppearance)appearance2).setAlignment(Alignment9.CENTER);
        appearance2.setState("mouseHover");
        widget.addBasicElement(appearance2);
        appearance2.onAttributesInitialized();
        final FontElement checkOut13 = FontElement.checkOut();
        checkOut13.setRenderer(Xulor.getInstance().getDocumentParser().getFont("styledLightFont"));
        checkOut13.setElementMap(elementMap);
        appearance2.addBasicElement(checkOut13);
        checkOut13.onAttributesInitialized();
        checkOut13.onChildrenAdded();
        final String id4 = "defaultDarkColor";
        final ColorElement checkOut14 = ColorElement.checkOut();
        checkOut14.setElementMap(elementMap);
        if (elementMap != null && id4 != null) {
            elementMap.add(id4, checkOut14);
        }
        checkOut14.setColor(new Color(0.29f, 0.17f, 0.07f, 1.0f));
        appearance2.addBasicElement(checkOut14);
        checkOut14.onAttributesInitialized();
        checkOut14.onChildrenAdded();
        final String id5 = "radioButtonBackgroundOver";
        final PixmapBackground checkOut15 = PixmapBackground.checkOut();
        checkOut15.setElementMap(elementMap);
        if (elementMap != null && id5 != null) {
            elementMap.add(id5, checkOut15);
        }
        checkOut15.setEnabled(false);
        checkOut15.setScaled(true);
        appearance2.addBasicElement(checkOut15);
        checkOut15.onAttributesInitialized();
        final PixmapElement checkOut16 = PixmapElement.checkOut();
        checkOut16.setElementMap(elementMap);
        checkOut16.setHeight(11);
        checkOut16.setPosition(Alignment17.CENTER);
        checkOut16.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut16.setWidth(16);
        checkOut16.setX(213);
        checkOut16.setY(103);
        checkOut15.addBasicElement(checkOut16);
        checkOut16.onAttributesInitialized();
        checkOut16.onChildrenAdded();
        checkOut15.onChildrenAdded();
        final String id6 = "radioButtonBorderOver";
        final PixmapBorder pixmapBorder2 = new PixmapBorder();
        pixmapBorder2.onCheckOut();
        pixmapBorder2.setElementMap(elementMap);
        if (elementMap != null && id6 != null) {
            elementMap.add(id6, pixmapBorder2);
        }
        pixmapBorder2.setEnabled(false);
        appearance2.addBasicElement(pixmapBorder2);
        pixmapBorder2.onAttributesInitialized();
        final PixmapElement checkOut17 = PixmapElement.checkOut();
        checkOut17.setElementMap(elementMap);
        checkOut17.setHeight(3);
        checkOut17.setPosition(Alignment17.NORTH_WEST);
        checkOut17.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut17.setWidth(3);
        checkOut17.setX(1014);
        checkOut17.setY(902);
        pixmapBorder2.addBasicElement(checkOut17);
        checkOut17.onAttributesInitialized();
        checkOut17.onChildrenAdded();
        final PixmapElement checkOut18 = PixmapElement.checkOut();
        checkOut18.setElementMap(elementMap);
        checkOut18.setHeight(3);
        checkOut18.setPosition(Alignment17.NORTH);
        checkOut18.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut18.setWidth(16);
        checkOut18.setX(978);
        checkOut18.setY(232);
        pixmapBorder2.addBasicElement(checkOut18);
        checkOut18.onAttributesInitialized();
        checkOut18.onChildrenAdded();
        final PixmapElement checkOut19 = PixmapElement.checkOut();
        checkOut19.setElementMap(elementMap);
        checkOut19.setHeight(3);
        checkOut19.setPosition(Alignment17.NORTH_EAST);
        checkOut19.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut19.setWidth(3);
        checkOut19.setX(974);
        checkOut19.setY(897);
        pixmapBorder2.addBasicElement(checkOut19);
        checkOut19.onAttributesInitialized();
        checkOut19.onChildrenAdded();
        final PixmapElement checkOut20 = PixmapElement.checkOut();
        checkOut20.setElementMap(elementMap);
        checkOut20.setHeight(11);
        checkOut20.setPosition(Alignment17.EAST);
        checkOut20.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut20.setWidth(3);
        checkOut20.setX(1012);
        checkOut20.setY(987);
        pixmapBorder2.addBasicElement(checkOut20);
        checkOut20.onAttributesInitialized();
        checkOut20.onChildrenAdded();
        final PixmapElement checkOut21 = PixmapElement.checkOut();
        checkOut21.setElementMap(elementMap);
        checkOut21.setHeight(3);
        checkOut21.setPosition(Alignment17.SOUTH_EAST);
        checkOut21.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut21.setWidth(3);
        checkOut21.setX(1009);
        checkOut21.setY(755);
        pixmapBorder2.addBasicElement(checkOut21);
        checkOut21.onAttributesInitialized();
        checkOut21.onChildrenAdded();
        final PixmapElement checkOut22 = PixmapElement.checkOut();
        checkOut22.setElementMap(elementMap);
        checkOut22.setHeight(3);
        checkOut22.setPosition(Alignment17.SOUTH);
        checkOut22.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut22.setWidth(16);
        checkOut22.setX(924);
        checkOut22.setY(236);
        pixmapBorder2.addBasicElement(checkOut22);
        checkOut22.onAttributesInitialized();
        checkOut22.onChildrenAdded();
        final PixmapElement checkOut23 = PixmapElement.checkOut();
        checkOut23.setElementMap(elementMap);
        checkOut23.setHeight(3);
        checkOut23.setPosition(Alignment17.SOUTH_WEST);
        checkOut23.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut23.setWidth(3);
        checkOut23.setX(1014);
        checkOut23.setY(908);
        pixmapBorder2.addBasicElement(checkOut23);
        checkOut23.onAttributesInitialized();
        checkOut23.onChildrenAdded();
        final PixmapElement checkOut24 = PixmapElement.checkOut();
        checkOut24.setElementMap(elementMap);
        checkOut24.setHeight(11);
        checkOut24.setPosition(Alignment17.WEST);
        checkOut24.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut24.setWidth(3);
        checkOut24.setX(1012);
        checkOut24.setY(973);
        pixmapBorder2.addBasicElement(checkOut24);
        checkOut24.onAttributesInitialized();
        checkOut24.onChildrenAdded();
        pixmapBorder2.onChildrenAdded();
        appearance2.onChildrenAdded();
        final DecoratorAppearance appearance3 = widget.getAppearance();
        appearance3.setElementMap(elementMap);
        ((TextWidgetAppearance)appearance3).setAlignment(Alignment9.CENTER);
        appearance3.setState("pressed");
        widget.addBasicElement(appearance3);
        appearance3.onAttributesInitialized();
        final FontElement checkOut25 = FontElement.checkOut();
        checkOut25.setRenderer(Xulor.getInstance().getDocumentParser().getFont("styledLightFont"));
        checkOut25.setElementMap(elementMap);
        appearance3.addBasicElement(checkOut25);
        checkOut25.onAttributesInitialized();
        checkOut25.onChildrenAdded();
        final String id7 = "defaultDarkColor";
        final ColorElement checkOut26 = ColorElement.checkOut();
        checkOut26.setElementMap(elementMap);
        if (elementMap != null && id7 != null) {
            elementMap.add(id7, checkOut26);
        }
        checkOut26.setColor(new Color(0.29f, 0.17f, 0.07f, 1.0f));
        appearance3.addBasicElement(checkOut26);
        checkOut26.onAttributesInitialized();
        checkOut26.onChildrenAdded();
        final String id8 = "radioButtonBackgroundPressed";
        final PixmapBackground checkOut27 = PixmapBackground.checkOut();
        checkOut27.setElementMap(elementMap);
        if (elementMap != null && id8 != null) {
            elementMap.add(id8, checkOut27);
        }
        checkOut27.setEnabled(false);
        checkOut27.setScaled(true);
        appearance3.addBasicElement(checkOut27);
        checkOut27.onAttributesInitialized();
        final PixmapElement checkOut28 = PixmapElement.checkOut();
        checkOut28.setElementMap(elementMap);
        checkOut28.setHeight(11);
        checkOut28.setPosition(Alignment17.CENTER);
        checkOut28.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut28.setWidth(16);
        checkOut28.setX(297);
        checkOut28.setY(103);
        checkOut27.addBasicElement(checkOut28);
        checkOut28.onAttributesInitialized();
        checkOut28.onChildrenAdded();
        checkOut27.onChildrenAdded();
        final String id9 = "radioButtonBorderPressed";
        final PixmapBorder pixmapBorder3 = new PixmapBorder();
        pixmapBorder3.onCheckOut();
        pixmapBorder3.setElementMap(elementMap);
        if (elementMap != null && id9 != null) {
            elementMap.add(id9, pixmapBorder3);
        }
        pixmapBorder3.setEnabled(false);
        appearance3.addBasicElement(pixmapBorder3);
        pixmapBorder3.onAttributesInitialized();
        final PixmapElement checkOut29 = PixmapElement.checkOut();
        checkOut29.setElementMap(elementMap);
        checkOut29.setHeight(3);
        checkOut29.setPosition(Alignment17.NORTH_WEST);
        checkOut29.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut29.setWidth(3);
        checkOut29.setX(1014);
        checkOut29.setY(896);
        pixmapBorder3.addBasicElement(checkOut29);
        checkOut29.onAttributesInitialized();
        checkOut29.onChildrenAdded();
        final PixmapElement checkOut30 = PixmapElement.checkOut();
        checkOut30.setElementMap(elementMap);
        checkOut30.setHeight(3);
        checkOut30.setPosition(Alignment17.NORTH);
        checkOut30.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut30.setWidth(16);
        checkOut30.setX(978);
        checkOut30.setY(238);
        pixmapBorder3.addBasicElement(checkOut30);
        checkOut30.onAttributesInitialized();
        checkOut30.onChildrenAdded();
        final PixmapElement checkOut31 = PixmapElement.checkOut();
        checkOut31.setElementMap(elementMap);
        checkOut31.setHeight(3);
        checkOut31.setPosition(Alignment17.NORTH_EAST);
        checkOut31.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut31.setWidth(3);
        checkOut31.setX(974);
        checkOut31.setY(909);
        pixmapBorder3.addBasicElement(checkOut31);
        checkOut31.onAttributesInitialized();
        checkOut31.onChildrenAdded();
        final PixmapElement checkOut32 = PixmapElement.checkOut();
        checkOut32.setElementMap(elementMap);
        checkOut32.setHeight(11);
        checkOut32.setPosition(Alignment17.EAST);
        checkOut32.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut32.setWidth(3);
        checkOut32.setX(1018);
        checkOut32.setY(973);
        pixmapBorder3.addBasicElement(checkOut32);
        checkOut32.onAttributesInitialized();
        checkOut32.onChildrenAdded();
        final PixmapElement checkOut33 = PixmapElement.checkOut();
        checkOut33.setElementMap(elementMap);
        checkOut33.setHeight(3);
        checkOut33.setPosition(Alignment17.SOUTH_EAST);
        checkOut33.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut33.setWidth(3);
        checkOut33.setX(974);
        checkOut33.setY(903);
        pixmapBorder3.addBasicElement(checkOut33);
        checkOut33.onAttributesInitialized();
        checkOut33.onChildrenAdded();
        final PixmapElement checkOut34 = PixmapElement.checkOut();
        checkOut34.setElementMap(elementMap);
        checkOut34.setHeight(3);
        checkOut34.setPosition(Alignment17.SOUTH);
        checkOut34.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut34.setWidth(16);
        checkOut34.setX(951);
        checkOut34.setY(236);
        pixmapBorder3.addBasicElement(checkOut34);
        checkOut34.onAttributesInitialized();
        checkOut34.onChildrenAdded();
        final PixmapElement checkOut35 = PixmapElement.checkOut();
        checkOut35.setElementMap(elementMap);
        checkOut35.setHeight(3);
        checkOut35.setPosition(Alignment17.SOUTH_WEST);
        checkOut35.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut35.setWidth(3);
        checkOut35.setX(974);
        checkOut35.setY(915);
        pixmapBorder3.addBasicElement(checkOut35);
        checkOut35.onAttributesInitialized();
        checkOut35.onChildrenAdded();
        final PixmapElement checkOut36 = PixmapElement.checkOut();
        checkOut36.setElementMap(elementMap);
        checkOut36.setHeight(11);
        checkOut36.setPosition(Alignment17.WEST);
        checkOut36.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut36.setWidth(3);
        checkOut36.setX(1018);
        checkOut36.setY(987);
        pixmapBorder3.addBasicElement(checkOut36);
        checkOut36.onAttributesInitialized();
        checkOut36.onChildrenAdded();
        pixmapBorder3.onChildrenAdded();
        appearance3.onChildrenAdded();
        final DecoratorAppearance appearance4 = widget.getAppearance();
        appearance4.setElementMap(elementMap);
        ((TextWidgetAppearance)appearance4).setAlignment(Alignment9.CENTER);
        appearance4.setState("selected");
        widget.addBasicElement(appearance4);
        appearance4.onAttributesInitialized();
        final FontElement checkOut37 = FontElement.checkOut();
        checkOut37.setRenderer(Xulor.getInstance().getDocumentParser().getFont("styledLightFont"));
        checkOut37.setElementMap(elementMap);
        appearance4.addBasicElement(checkOut37);
        checkOut37.onAttributesInitialized();
        checkOut37.onChildrenAdded();
        final String id10 = "defaultDarkColor";
        final ColorElement checkOut38 = ColorElement.checkOut();
        checkOut38.setElementMap(elementMap);
        if (elementMap != null && id10 != null) {
            elementMap.add(id10, checkOut38);
        }
        checkOut38.setColor(new Color(0.29f, 0.17f, 0.07f, 1.0f));
        appearance4.addBasicElement(checkOut38);
        checkOut38.onAttributesInitialized();
        checkOut38.onChildrenAdded();
        final String id11 = "radioButtonBackgroundDefaultSelected";
        final PixmapBackground checkOut39 = PixmapBackground.checkOut();
        checkOut39.setElementMap(elementMap);
        if (elementMap != null && id11 != null) {
            elementMap.add(id11, checkOut39);
        }
        checkOut39.setScaled(true);
        appearance4.addBasicElement(checkOut39);
        checkOut39.onAttributesInitialized();
        final PixmapElement checkOut40 = PixmapElement.checkOut();
        checkOut40.setElementMap(elementMap);
        checkOut40.setHeight(11);
        checkOut40.setPosition(Alignment17.CENTER);
        checkOut40.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut40.setWidth(16);
        checkOut40.setX(297);
        checkOut40.setY(103);
        checkOut39.addBasicElement(checkOut40);
        checkOut40.onAttributesInitialized();
        checkOut40.onChildrenAdded();
        checkOut39.onChildrenAdded();
        final String id12 = "radioButtonBorderDefaultSelected";
        final PixmapBorder pixmapBorder4 = new PixmapBorder();
        pixmapBorder4.onCheckOut();
        pixmapBorder4.setElementMap(elementMap);
        if (elementMap != null && id12 != null) {
            elementMap.add(id12, pixmapBorder4);
        }
        pixmapBorder4.setEnabled(false);
        appearance4.addBasicElement(pixmapBorder4);
        pixmapBorder4.onAttributesInitialized();
        final PixmapElement checkOut41 = PixmapElement.checkOut();
        checkOut41.setElementMap(elementMap);
        checkOut41.setHeight(3);
        checkOut41.setPosition(Alignment17.NORTH_WEST);
        checkOut41.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut41.setWidth(3);
        checkOut41.setX(1014);
        checkOut41.setY(896);
        pixmapBorder4.addBasicElement(checkOut41);
        checkOut41.onAttributesInitialized();
        checkOut41.onChildrenAdded();
        final PixmapElement checkOut42 = PixmapElement.checkOut();
        checkOut42.setElementMap(elementMap);
        checkOut42.setHeight(3);
        checkOut42.setPosition(Alignment17.NORTH);
        checkOut42.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut42.setWidth(16);
        checkOut42.setX(978);
        checkOut42.setY(238);
        pixmapBorder4.addBasicElement(checkOut42);
        checkOut42.onAttributesInitialized();
        checkOut42.onChildrenAdded();
        this.method0(pixmapBorder4);
        this.method1(pixmapBorder4);
        this.method2(pixmapBorder4);
        this.method3(pixmapBorder4);
        this.method4(pixmapBorder4);
        this.method5(pixmapBorder4);
        pixmapBorder4.onChildrenAdded();
        appearance4.onChildrenAdded();
        this.method6(widget);
        this.method7(widget);
    }
    
    public BasicElement method0(final BasicElement basicElement) {
        final ElementMap elementMap = this.elementMaps.peek();
        final PixmapElement checkOut = PixmapElement.checkOut();
        checkOut.setElementMap(elementMap);
        checkOut.setHeight(3);
        checkOut.setPosition(Alignment17.NORTH_EAST);
        checkOut.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut.setWidth(3);
        checkOut.setX(974);
        checkOut.setY(909);
        basicElement.addBasicElement(checkOut);
        checkOut.onAttributesInitialized();
        checkOut.onChildrenAdded();
        return checkOut;
    }
    
    public BasicElement method1(final BasicElement basicElement) {
        final ElementMap elementMap = this.elementMaps.peek();
        final PixmapElement checkOut = PixmapElement.checkOut();
        checkOut.setElementMap(elementMap);
        checkOut.setHeight(11);
        checkOut.setPosition(Alignment17.EAST);
        checkOut.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut.setWidth(3);
        checkOut.setX(1018);
        checkOut.setY(973);
        basicElement.addBasicElement(checkOut);
        checkOut.onAttributesInitialized();
        checkOut.onChildrenAdded();
        return checkOut;
    }
    
    public BasicElement method2(final BasicElement basicElement) {
        final ElementMap elementMap = this.elementMaps.peek();
        final PixmapElement checkOut = PixmapElement.checkOut();
        checkOut.setElementMap(elementMap);
        checkOut.setHeight(3);
        checkOut.setPosition(Alignment17.SOUTH_EAST);
        checkOut.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut.setWidth(3);
        checkOut.setX(974);
        checkOut.setY(903);
        basicElement.addBasicElement(checkOut);
        checkOut.onAttributesInitialized();
        checkOut.onChildrenAdded();
        return checkOut;
    }
    
    public BasicElement method3(final BasicElement basicElement) {
        final ElementMap elementMap = this.elementMaps.peek();
        final PixmapElement checkOut = PixmapElement.checkOut();
        checkOut.setElementMap(elementMap);
        checkOut.setHeight(3);
        checkOut.setPosition(Alignment17.SOUTH);
        checkOut.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut.setWidth(16);
        checkOut.setX(951);
        checkOut.setY(236);
        basicElement.addBasicElement(checkOut);
        checkOut.onAttributesInitialized();
        checkOut.onChildrenAdded();
        return checkOut;
    }
    
    public BasicElement method4(final BasicElement basicElement) {
        final ElementMap elementMap = this.elementMaps.peek();
        final PixmapElement checkOut = PixmapElement.checkOut();
        checkOut.setElementMap(elementMap);
        checkOut.setHeight(3);
        checkOut.setPosition(Alignment17.SOUTH_WEST);
        checkOut.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut.setWidth(3);
        checkOut.setX(974);
        checkOut.setY(915);
        basicElement.addBasicElement(checkOut);
        checkOut.onAttributesInitialized();
        checkOut.onChildrenAdded();
        return checkOut;
    }
    
    public BasicElement method5(final BasicElement basicElement) {
        final ElementMap elementMap = this.elementMaps.peek();
        final PixmapElement checkOut = PixmapElement.checkOut();
        checkOut.setElementMap(elementMap);
        checkOut.setHeight(11);
        checkOut.setPosition(Alignment17.WEST);
        checkOut.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut.setWidth(3);
        checkOut.setX(1018);
        checkOut.setY(987);
        basicElement.addBasicElement(checkOut);
        checkOut.onAttributesInitialized();
        checkOut.onChildrenAdded();
        return checkOut;
    }
    
    public BasicElement method6(final BasicElement basicElement) {
        final ElementMap elementMap = this.elementMaps.peek();
        final DecoratorAppearance appearance = ((Widget)basicElement).getAppearance();
        appearance.setElementMap(elementMap);
        ((TextWidgetAppearance)appearance).setAlignment(Alignment9.CENTER);
        appearance.setState("mouseHoverSelected");
        basicElement.addBasicElement(appearance);
        appearance.onAttributesInitialized();
        final FontElement checkOut = FontElement.checkOut();
        checkOut.setRenderer(Xulor.getInstance().getDocumentParser().getFont("styledLightFont"));
        checkOut.setElementMap(elementMap);
        appearance.addBasicElement(checkOut);
        checkOut.onAttributesInitialized();
        checkOut.onChildrenAdded();
        final String id = "defaultDarkColor";
        final ColorElement checkOut2 = ColorElement.checkOut();
        checkOut2.setElementMap(elementMap);
        if (elementMap != null && id != null) {
            elementMap.add(id, checkOut2);
        }
        checkOut2.setColor(new Color(0.29f, 0.17f, 0.07f, 1.0f));
        appearance.addBasicElement(checkOut2);
        checkOut2.onAttributesInitialized();
        checkOut2.onChildrenAdded();
        final String id2 = "radioButtonBackgroundOverSelected";
        final PixmapBackground checkOut3 = PixmapBackground.checkOut();
        checkOut3.setElementMap(elementMap);
        if (elementMap != null && id2 != null) {
            elementMap.add(id2, checkOut3);
        }
        checkOut3.setEnabled(false);
        checkOut3.setScaled(true);
        appearance.addBasicElement(checkOut3);
        checkOut3.onAttributesInitialized();
        final PixmapElement checkOut4 = PixmapElement.checkOut();
        checkOut4.setElementMap(elementMap);
        checkOut4.setHeight(11);
        checkOut4.setPosition(Alignment17.CENTER);
        checkOut4.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut4.setWidth(16);
        checkOut4.setX(297);
        checkOut4.setY(103);
        checkOut3.addBasicElement(checkOut4);
        checkOut4.onAttributesInitialized();
        checkOut4.onChildrenAdded();
        checkOut3.onChildrenAdded();
        final String id3 = "radioButtonBorderOverSelected";
        final PixmapBorder pixmapBorder = new PixmapBorder();
        pixmapBorder.onCheckOut();
        pixmapBorder.setElementMap(elementMap);
        if (elementMap != null && id3 != null) {
            elementMap.add(id3, pixmapBorder);
        }
        pixmapBorder.setEnabled(false);
        appearance.addBasicElement(pixmapBorder);
        pixmapBorder.onAttributesInitialized();
        final PixmapElement checkOut5 = PixmapElement.checkOut();
        checkOut5.setElementMap(elementMap);
        checkOut5.setHeight(3);
        checkOut5.setPosition(Alignment17.NORTH_WEST);
        checkOut5.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut5.setWidth(3);
        checkOut5.setX(1014);
        checkOut5.setY(896);
        pixmapBorder.addBasicElement(checkOut5);
        checkOut5.onAttributesInitialized();
        checkOut5.onChildrenAdded();
        final PixmapElement checkOut6 = PixmapElement.checkOut();
        checkOut6.setElementMap(elementMap);
        checkOut6.setHeight(3);
        checkOut6.setPosition(Alignment17.NORTH);
        checkOut6.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut6.setWidth(16);
        checkOut6.setX(978);
        checkOut6.setY(238);
        pixmapBorder.addBasicElement(checkOut6);
        checkOut6.onAttributesInitialized();
        checkOut6.onChildrenAdded();
        final PixmapElement checkOut7 = PixmapElement.checkOut();
        checkOut7.setElementMap(elementMap);
        checkOut7.setHeight(3);
        checkOut7.setPosition(Alignment17.NORTH_EAST);
        checkOut7.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut7.setWidth(3);
        checkOut7.setX(974);
        checkOut7.setY(909);
        pixmapBorder.addBasicElement(checkOut7);
        checkOut7.onAttributesInitialized();
        checkOut7.onChildrenAdded();
        final PixmapElement checkOut8 = PixmapElement.checkOut();
        checkOut8.setElementMap(elementMap);
        checkOut8.setHeight(11);
        checkOut8.setPosition(Alignment17.EAST);
        checkOut8.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut8.setWidth(3);
        checkOut8.setX(1018);
        checkOut8.setY(973);
        pixmapBorder.addBasicElement(checkOut8);
        checkOut8.onAttributesInitialized();
        checkOut8.onChildrenAdded();
        final PixmapElement checkOut9 = PixmapElement.checkOut();
        checkOut9.setElementMap(elementMap);
        checkOut9.setHeight(3);
        checkOut9.setPosition(Alignment17.SOUTH_EAST);
        checkOut9.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut9.setWidth(3);
        checkOut9.setX(974);
        checkOut9.setY(903);
        pixmapBorder.addBasicElement(checkOut9);
        checkOut9.onAttributesInitialized();
        checkOut9.onChildrenAdded();
        final PixmapElement checkOut10 = PixmapElement.checkOut();
        checkOut10.setElementMap(elementMap);
        checkOut10.setHeight(3);
        checkOut10.setPosition(Alignment17.SOUTH);
        checkOut10.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut10.setWidth(16);
        checkOut10.setX(951);
        checkOut10.setY(236);
        pixmapBorder.addBasicElement(checkOut10);
        checkOut10.onAttributesInitialized();
        checkOut10.onChildrenAdded();
        final PixmapElement checkOut11 = PixmapElement.checkOut();
        checkOut11.setElementMap(elementMap);
        checkOut11.setHeight(3);
        checkOut11.setPosition(Alignment17.SOUTH_WEST);
        checkOut11.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut11.setWidth(3);
        checkOut11.setX(974);
        checkOut11.setY(915);
        pixmapBorder.addBasicElement(checkOut11);
        checkOut11.onAttributesInitialized();
        checkOut11.onChildrenAdded();
        final PixmapElement checkOut12 = PixmapElement.checkOut();
        checkOut12.setElementMap(elementMap);
        checkOut12.setHeight(11);
        checkOut12.setPosition(Alignment17.WEST);
        checkOut12.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut12.setWidth(3);
        checkOut12.setX(1018);
        checkOut12.setY(987);
        pixmapBorder.addBasicElement(checkOut12);
        checkOut12.onAttributesInitialized();
        checkOut12.onChildrenAdded();
        pixmapBorder.onChildrenAdded();
        appearance.onChildrenAdded();
        return appearance;
    }
    
    public BasicElement method7(final BasicElement basicElement) {
        final ElementMap elementMap = this.elementMaps.peek();
        final DecoratorAppearance appearance = ((Widget)basicElement).getAppearance();
        appearance.setElementMap(elementMap);
        ((TextWidgetAppearance)appearance).setAlignment(Alignment9.CENTER);
        appearance.setState("pressedSelected");
        basicElement.addBasicElement(appearance);
        appearance.onAttributesInitialized();
        final FontElement checkOut = FontElement.checkOut();
        checkOut.setRenderer(Xulor.getInstance().getDocumentParser().getFont("styledLightFont"));
        checkOut.setElementMap(elementMap);
        appearance.addBasicElement(checkOut);
        checkOut.onAttributesInitialized();
        checkOut.onChildrenAdded();
        final String id = "defaultDarkColor";
        final ColorElement checkOut2 = ColorElement.checkOut();
        checkOut2.setElementMap(elementMap);
        if (elementMap != null && id != null) {
            elementMap.add(id, checkOut2);
        }
        checkOut2.setColor(new Color(0.29f, 0.17f, 0.07f, 1.0f));
        appearance.addBasicElement(checkOut2);
        checkOut2.onAttributesInitialized();
        checkOut2.onChildrenAdded();
        final String id2 = "radioButtonBackgroundPressedSelected";
        final PixmapBackground checkOut3 = PixmapBackground.checkOut();
        checkOut3.setElementMap(elementMap);
        if (elementMap != null && id2 != null) {
            elementMap.add(id2, checkOut3);
        }
        checkOut3.setEnabled(false);
        checkOut3.setScaled(true);
        appearance.addBasicElement(checkOut3);
        checkOut3.onAttributesInitialized();
        final PixmapElement checkOut4 = PixmapElement.checkOut();
        checkOut4.setElementMap(elementMap);
        checkOut4.setHeight(11);
        checkOut4.setPosition(Alignment17.CENTER);
        checkOut4.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut4.setWidth(16);
        checkOut4.setX(297);
        checkOut4.setY(103);
        checkOut3.addBasicElement(checkOut4);
        checkOut4.onAttributesInitialized();
        checkOut4.onChildrenAdded();
        checkOut3.onChildrenAdded();
        final String id3 = "radioButtonBorderPressedSelected";
        final PixmapBorder pixmapBorder = new PixmapBorder();
        pixmapBorder.onCheckOut();
        pixmapBorder.setElementMap(elementMap);
        if (elementMap != null && id3 != null) {
            elementMap.add(id3, pixmapBorder);
        }
        pixmapBorder.setEnabled(false);
        appearance.addBasicElement(pixmapBorder);
        pixmapBorder.onAttributesInitialized();
        final PixmapElement checkOut5 = PixmapElement.checkOut();
        checkOut5.setElementMap(elementMap);
        checkOut5.setHeight(3);
        checkOut5.setPosition(Alignment17.NORTH_WEST);
        checkOut5.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut5.setWidth(3);
        checkOut5.setX(1014);
        checkOut5.setY(896);
        pixmapBorder.addBasicElement(checkOut5);
        checkOut5.onAttributesInitialized();
        checkOut5.onChildrenAdded();
        final PixmapElement checkOut6 = PixmapElement.checkOut();
        checkOut6.setElementMap(elementMap);
        checkOut6.setHeight(3);
        checkOut6.setPosition(Alignment17.NORTH);
        checkOut6.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut6.setWidth(16);
        checkOut6.setX(978);
        checkOut6.setY(238);
        pixmapBorder.addBasicElement(checkOut6);
        checkOut6.onAttributesInitialized();
        checkOut6.onChildrenAdded();
        final PixmapElement checkOut7 = PixmapElement.checkOut();
        checkOut7.setElementMap(elementMap);
        checkOut7.setHeight(3);
        checkOut7.setPosition(Alignment17.NORTH_EAST);
        checkOut7.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut7.setWidth(3);
        checkOut7.setX(974);
        checkOut7.setY(909);
        pixmapBorder.addBasicElement(checkOut7);
        checkOut7.onAttributesInitialized();
        checkOut7.onChildrenAdded();
        final PixmapElement checkOut8 = PixmapElement.checkOut();
        checkOut8.setElementMap(elementMap);
        checkOut8.setHeight(11);
        checkOut8.setPosition(Alignment17.EAST);
        checkOut8.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut8.setWidth(3);
        checkOut8.setX(1018);
        checkOut8.setY(973);
        pixmapBorder.addBasicElement(checkOut8);
        checkOut8.onAttributesInitialized();
        checkOut8.onChildrenAdded();
        final PixmapElement checkOut9 = PixmapElement.checkOut();
        checkOut9.setElementMap(elementMap);
        checkOut9.setHeight(3);
        checkOut9.setPosition(Alignment17.SOUTH_EAST);
        checkOut9.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut9.setWidth(3);
        checkOut9.setX(974);
        checkOut9.setY(903);
        pixmapBorder.addBasicElement(checkOut9);
        checkOut9.onAttributesInitialized();
        checkOut9.onChildrenAdded();
        final PixmapElement checkOut10 = PixmapElement.checkOut();
        checkOut10.setElementMap(elementMap);
        checkOut10.setHeight(3);
        checkOut10.setPosition(Alignment17.SOUTH);
        checkOut10.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut10.setWidth(16);
        checkOut10.setX(951);
        checkOut10.setY(236);
        pixmapBorder.addBasicElement(checkOut10);
        checkOut10.onAttributesInitialized();
        checkOut10.onChildrenAdded();
        final PixmapElement checkOut11 = PixmapElement.checkOut();
        checkOut11.setElementMap(elementMap);
        checkOut11.setHeight(3);
        checkOut11.setPosition(Alignment17.SOUTH_WEST);
        checkOut11.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut11.setWidth(3);
        checkOut11.setX(974);
        checkOut11.setY(915);
        pixmapBorder.addBasicElement(checkOut11);
        checkOut11.onAttributesInitialized();
        checkOut11.onChildrenAdded();
        final PixmapElement checkOut12 = PixmapElement.checkOut();
        checkOut12.setElementMap(elementMap);
        checkOut12.setHeight(11);
        checkOut12.setPosition(Alignment17.WEST);
        checkOut12.setTexture(this.doc.getTexture("preWorld_0.tga"));
        checkOut12.setWidth(3);
        checkOut12.setX(1018);
        checkOut12.setY(987);
        pixmapBorder.addBasicElement(checkOut12);
        checkOut12.onAttributesInitialized();
        checkOut12.onChildrenAdded();
        pixmapBorder.onChildrenAdded();
        appearance.onChildrenAdded();
        return appearance;
    }
}
