package com.ankamagames.wakfu.client.ui.theme;

import java.util.*;
import com.ankamagames.xulor2.component.*;
import com.ankamagames.xulor2.core.*;
import com.ankamagames.xulor2.util.alignment.*;
import com.ankamagames.framework.graphics.engine.geometry.*;
import com.ankamagames.xulor2.decorator.*;
import com.ankamagames.xulor2.appearance.*;

public class ScrollContainerEncyclopedia$HorizontalScrollbar$HorizontalSlider$HorizontalButton implements StyleSetter
{
    private DocumentParser doc;
    private Stack<ElementMap> elementMaps;
    
    public ScrollContainerEncyclopedia$HorizontalScrollbar$HorizontalSlider$HorizontalButton() {
        super();
        this.elementMaps = new Stack<ElementMap>();
    }
    
    @Override
    public void applyStyle(final ElementMap item, final DocumentParser doc, final Widget widget) {
        this.doc = doc;
        this.elementMaps.push(item);
        final ElementMap elementMap = this.elementMaps.peek();
        final DecoratorAppearance appearance = widget.getAppearance();
        appearance.setElementMap(elementMap);
        appearance.setState("default");
        widget.addBasicElement(appearance);
        appearance.onAttributesInitialized();
        final PixmapBorder element = new PixmapBorder();
        element.onCheckOut();
        element.setElementMap(elementMap);
        appearance.addBasicElement(element);
        element.onAttributesInitialized();
        final PixmapElement checkOut = PixmapElement.checkOut();
        checkOut.setElementMap(elementMap);
        checkOut.setHeight(28);
        checkOut.setPosition(Alignment17.SOUTH_WEST);
        checkOut.setRotation(GeometrySprite.SpriteRotation.QUARTER_COUNTER_CLOCKWISE);
        checkOut.setTexture(this.doc.getTexture("default_0.tga"));
        checkOut.setWidth(11);
        checkOut.setX(307);
        checkOut.setY(349);
        element.addBasicElement(checkOut);
        checkOut.onAttributesInitialized();
        checkOut.onChildrenAdded();
        final PixmapElement checkOut2 = PixmapElement.checkOut();
        checkOut2.setElementMap(elementMap);
        checkOut2.setHeight(28);
        checkOut2.setPosition(Alignment17.WEST);
        checkOut2.setRotation(GeometrySprite.SpriteRotation.QUARTER_COUNTER_CLOCKWISE);
        checkOut2.setTexture(this.doc.getTexture("default_0.tga"));
        checkOut2.setWidth(1);
        checkOut2.setX(487);
        checkOut2.setY(506);
        element.addBasicElement(checkOut2);
        checkOut2.onAttributesInitialized();
        checkOut2.onChildrenAdded();
        final PixmapElement checkOut3 = PixmapElement.checkOut();
        checkOut3.setElementMap(elementMap);
        checkOut3.setHeight(28);
        checkOut3.setPosition(Alignment17.NORTH_WEST);
        checkOut3.setRotation(GeometrySprite.SpriteRotation.QUARTER_COUNTER_CLOCKWISE);
        checkOut3.setTexture(this.doc.getTexture("default_0.tga"));
        checkOut3.setWidth(11);
        checkOut3.setX(389);
        checkOut3.setY(285);
        element.addBasicElement(checkOut3);
        checkOut3.onAttributesInitialized();
        checkOut3.onChildrenAdded();
        final PixmapElement checkOut4 = PixmapElement.checkOut();
        checkOut4.setElementMap(elementMap);
        checkOut4.setHeight(1);
        checkOut4.setPosition(Alignment17.NORTH);
        checkOut4.setRotation(GeometrySprite.SpriteRotation.QUARTER_COUNTER_CLOCKWISE);
        checkOut4.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut4.setWidth(11);
        checkOut4.setX(767);
        checkOut4.setY(181);
        element.addBasicElement(checkOut4);
        checkOut4.onAttributesInitialized();
        checkOut4.onChildrenAdded();
        final PixmapElement checkOut5 = PixmapElement.checkOut();
        checkOut5.setElementMap(elementMap);
        checkOut5.setHeight(28);
        checkOut5.setPosition(Alignment17.NORTH_EAST);
        checkOut5.setRotation(GeometrySprite.SpriteRotation.QUARTER_COUNTER_CLOCKWISE);
        checkOut5.setTexture(this.doc.getTexture("default_0.tga"));
        checkOut5.setWidth(11);
        checkOut5.setX(389);
        checkOut5.setY(347);
        element.addBasicElement(checkOut5);
        checkOut5.onAttributesInitialized();
        checkOut5.onChildrenAdded();
        final PixmapElement checkOut6 = PixmapElement.checkOut();
        checkOut6.setElementMap(elementMap);
        checkOut6.setHeight(28);
        checkOut6.setPosition(Alignment17.EAST);
        checkOut6.setRotation(GeometrySprite.SpriteRotation.QUARTER_COUNTER_CLOCKWISE);
        checkOut6.setTexture(this.doc.getTexture("default_0.tga"));
        checkOut6.setWidth(1);
        checkOut6.setX(319);
        checkOut6.setY(505);
        element.addBasicElement(checkOut6);
        checkOut6.onAttributesInitialized();
        checkOut6.onChildrenAdded();
        final PixmapElement checkOut7 = PixmapElement.checkOut();
        checkOut7.setElementMap(elementMap);
        checkOut7.setHeight(28);
        checkOut7.setPosition(Alignment17.SOUTH_EAST);
        checkOut7.setRotation(GeometrySprite.SpriteRotation.QUARTER_COUNTER_CLOCKWISE);
        checkOut7.setTexture(this.doc.getTexture("default_0.tga"));
        checkOut7.setWidth(11);
        checkOut7.setX(477);
        checkOut7.setY(292);
        element.addBasicElement(checkOut7);
        checkOut7.onAttributesInitialized();
        checkOut7.onChildrenAdded();
        final PixmapElement checkOut8 = PixmapElement.checkOut();
        checkOut8.setElementMap(elementMap);
        checkOut8.setHeight(1);
        checkOut8.setPosition(Alignment17.SOUTH);
        checkOut8.setRotation(GeometrySprite.SpriteRotation.QUARTER_COUNTER_CLOCKWISE);
        checkOut8.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut8.setWidth(11);
        checkOut8.setX(502);
        checkOut8.setY(146);
        element.addBasicElement(checkOut8);
        checkOut8.onAttributesInitialized();
        checkOut8.onChildrenAdded();
        element.onChildrenAdded();
        final PixmapBackground checkOut9 = PixmapBackground.checkOut();
        checkOut9.setElementMap(elementMap);
        checkOut9.setEnabled(true);
        checkOut9.setScaled(true);
        appearance.addBasicElement(checkOut9);
        checkOut9.onAttributesInitialized();
        final PixmapElement checkOut10 = PixmapElement.checkOut();
        checkOut10.setElementMap(elementMap);
        checkOut10.setHeight(1);
        checkOut10.setPosition(Alignment17.CENTER);
        checkOut10.setRotation(GeometrySprite.SpriteRotation.QUARTER_COUNTER_CLOCKWISE);
        checkOut10.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut10.setWidth(1);
        checkOut10.setX(808);
        checkOut10.setY(177);
        checkOut9.addBasicElement(checkOut10);
        checkOut10.onAttributesInitialized();
        checkOut10.onChildrenAdded();
        checkOut9.onChildrenAdded();
        appearance.onChildrenAdded();
        final DecoratorAppearance appearance2 = widget.getAppearance();
        appearance2.setElementMap(elementMap);
        appearance2.setState("mouseHover");
        widget.addBasicElement(appearance2);
        appearance2.onAttributesInitialized();
        final PixmapBorder element2 = new PixmapBorder();
        element2.onCheckOut();
        element2.setElementMap(elementMap);
        appearance2.addBasicElement(element2);
        element2.onAttributesInitialized();
        final PixmapElement checkOut11 = PixmapElement.checkOut();
        checkOut11.setElementMap(elementMap);
        checkOut11.setHeight(28);
        checkOut11.setPosition(Alignment17.SOUTH_WEST);
        checkOut11.setRotation(GeometrySprite.SpriteRotation.QUARTER_COUNTER_CLOCKWISE);
        checkOut11.setTexture(this.doc.getTexture("default_0.tga"));
        checkOut11.setWidth(11);
        checkOut11.setX(396);
        checkOut11.setY(414);
        element2.addBasicElement(checkOut11);
        checkOut11.onAttributesInitialized();
        checkOut11.onChildrenAdded();
        final PixmapElement checkOut12 = PixmapElement.checkOut();
        checkOut12.setElementMap(elementMap);
        checkOut12.setHeight(28);
        checkOut12.setPosition(Alignment17.WEST);
        checkOut12.setRotation(GeometrySprite.SpriteRotation.QUARTER_COUNTER_CLOCKWISE);
        checkOut12.setWidth(0);
        checkOut12.setX(214);
        checkOut12.setY(405);
        element2.addBasicElement(checkOut12);
        checkOut12.onAttributesInitialized();
        checkOut12.onChildrenAdded();
        final PixmapElement checkOut13 = PixmapElement.checkOut();
        checkOut13.setElementMap(elementMap);
        checkOut13.setHeight(28);
        checkOut13.setPosition(Alignment17.NORTH_WEST);
        checkOut13.setRotation(GeometrySprite.SpriteRotation.QUARTER_COUNTER_CLOCKWISE);
        checkOut13.setTexture(this.doc.getTexture("default_0.tga"));
        checkOut13.setWidth(11);
        checkOut13.setX(307);
        checkOut13.setY(287);
        element2.addBasicElement(checkOut13);
        checkOut13.onAttributesInitialized();
        checkOut13.onChildrenAdded();
        final PixmapElement checkOut14 = PixmapElement.checkOut();
        checkOut14.setElementMap(elementMap);
        checkOut14.setHeight(1);
        checkOut14.setPosition(Alignment17.NORTH);
        checkOut14.setRotation(GeometrySprite.SpriteRotation.QUARTER_COUNTER_CLOCKWISE);
        checkOut14.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut14.setWidth(11);
        checkOut14.setX(51);
        checkOut14.setY(137);
        element2.addBasicElement(checkOut14);
        checkOut14.onAttributesInitialized();
        checkOut14.onChildrenAdded();
        final PixmapElement checkOut15 = PixmapElement.checkOut();
        checkOut15.setElementMap(elementMap);
        checkOut15.setHeight(28);
        checkOut15.setPosition(Alignment17.NORTH_EAST);
        checkOut15.setRotation(GeometrySprite.SpriteRotation.QUARTER_COUNTER_CLOCKWISE);
        checkOut15.setTexture(this.doc.getTexture("default_0.tga"));
        checkOut15.setWidth(11);
        checkOut15.setX(307);
        checkOut15.setY(411);
        element2.addBasicElement(checkOut15);
        checkOut15.onAttributesInitialized();
        checkOut15.onChildrenAdded();
        final PixmapElement checkOut16 = PixmapElement.checkOut();
        checkOut16.setElementMap(elementMap);
        checkOut16.setHeight(28);
        checkOut16.setPosition(Alignment17.EAST);
        checkOut16.setRotation(GeometrySprite.SpriteRotation.QUARTER_COUNTER_CLOCKWISE);
        checkOut16.setWidth(0);
        checkOut16.setX(214);
        checkOut16.setY(434);
        element2.addBasicElement(checkOut16);
        checkOut16.onAttributesInitialized();
        checkOut16.onChildrenAdded();
        final PixmapElement checkOut17 = PixmapElement.checkOut();
        checkOut17.setElementMap(elementMap);
        checkOut17.setHeight(28);
        checkOut17.setPosition(Alignment17.SOUTH_EAST);
        checkOut17.setRotation(GeometrySprite.SpriteRotation.QUARTER_COUNTER_CLOCKWISE);
        checkOut17.setTexture(this.doc.getTexture("default_0.tga"));
        checkOut17.setWidth(11);
        checkOut17.setX(307);
        checkOut17.setY(318);
        element2.addBasicElement(checkOut17);
        checkOut17.onAttributesInitialized();
        checkOut17.onChildrenAdded();
        final PixmapElement checkOut18 = PixmapElement.checkOut();
        checkOut18.setElementMap(elementMap);
        checkOut18.setHeight(1);
        checkOut18.setPosition(Alignment17.SOUTH);
        checkOut18.setRotation(GeometrySprite.SpriteRotation.QUARTER_COUNTER_CLOCKWISE);
        checkOut18.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut18.setWidth(11);
        checkOut18.setX(588);
        checkOut18.setY(198);
        element2.addBasicElement(checkOut18);
        checkOut18.onAttributesInitialized();
        checkOut18.onChildrenAdded();
        element2.onChildrenAdded();
        final PixmapBackground checkOut19 = PixmapBackground.checkOut();
        checkOut19.setElementMap(elementMap);
        checkOut19.setEnabled(true);
        checkOut19.setScaled(true);
        appearance2.addBasicElement(checkOut19);
        checkOut19.onAttributesInitialized();
        final PixmapElement checkOut20 = PixmapElement.checkOut();
        checkOut20.setElementMap(elementMap);
        checkOut20.setHeight(1);
        checkOut20.setPosition(Alignment17.CENTER);
        checkOut20.setRotation(GeometrySprite.SpriteRotation.QUARTER_COUNTER_CLOCKWISE);
        checkOut20.setWidth(0);
        checkOut20.setX(214);
        checkOut20.setY(433);
        checkOut19.addBasicElement(checkOut20);
        checkOut20.onAttributesInitialized();
        checkOut20.onChildrenAdded();
        checkOut19.onChildrenAdded();
        appearance2.onChildrenAdded();
        final DecoratorAppearance appearance3 = widget.getAppearance();
        appearance3.setElementMap(elementMap);
        appearance3.setState("pressed");
        widget.addBasicElement(appearance3);
        appearance3.onAttributesInitialized();
        final PixmapBorder element3 = new PixmapBorder();
        element3.onCheckOut();
        element3.setElementMap(elementMap);
        appearance3.addBasicElement(element3);
        element3.onAttributesInitialized();
        final PixmapElement checkOut21 = PixmapElement.checkOut();
        checkOut21.setElementMap(elementMap);
        checkOut21.setHeight(28);
        checkOut21.setPosition(Alignment17.SOUTH_WEST);
        checkOut21.setRotation(GeometrySprite.SpriteRotation.QUARTER_COUNTER_CLOCKWISE);
        checkOut21.setTexture(this.doc.getTexture("default_0.tga"));
        checkOut21.setWidth(11);
        checkOut21.setX(890);
        checkOut21.setY(416);
        element3.addBasicElement(checkOut21);
        checkOut21.onAttributesInitialized();
        checkOut21.onChildrenAdded();
        final PixmapElement checkOut22 = PixmapElement.checkOut();
        checkOut22.setElementMap(elementMap);
        checkOut22.setHeight(28);
        checkOut22.setPosition(Alignment17.WEST);
        checkOut22.setRotation(GeometrySprite.SpriteRotation.QUARTER_COUNTER_CLOCKWISE);
        checkOut22.setWidth(0);
        checkOut22.setX(214);
        checkOut22.setY(405);
        element3.addBasicElement(checkOut22);
        checkOut22.onAttributesInitialized();
        checkOut22.onChildrenAdded();
        final PixmapElement checkOut23 = PixmapElement.checkOut();
        checkOut23.setElementMap(elementMap);
        checkOut23.setHeight(28);
        checkOut23.setPosition(Alignment17.NORTH_WEST);
        checkOut23.setRotation(GeometrySprite.SpriteRotation.QUARTER_COUNTER_CLOCKWISE);
        checkOut23.setTexture(this.doc.getTexture("default_0.tga"));
        checkOut23.setWidth(11);
        checkOut23.setX(477);
        checkOut23.setY(323);
        element3.addBasicElement(checkOut23);
        checkOut23.onAttributesInitialized();
        checkOut23.onChildrenAdded();
        final PixmapElement checkOut24 = PixmapElement.checkOut();
        checkOut24.setElementMap(elementMap);
        checkOut24.setHeight(1);
        checkOut24.setPosition(Alignment17.NORTH);
        checkOut24.setRotation(GeometrySprite.SpriteRotation.QUARTER_COUNTER_CLOCKWISE);
        checkOut24.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut24.setWidth(11);
        checkOut24.setX(982);
        checkOut24.setY(137);
        element3.addBasicElement(checkOut24);
        checkOut24.onAttributesInitialized();
        checkOut24.onChildrenAdded();
        final PixmapElement checkOut25 = PixmapElement.checkOut();
        checkOut25.setElementMap(elementMap);
        checkOut25.setHeight(28);
        checkOut25.setPosition(Alignment17.NORTH_EAST);
        checkOut25.setRotation(GeometrySprite.SpriteRotation.QUARTER_COUNTER_CLOCKWISE);
        checkOut25.setTexture(this.doc.getTexture("default_0.tga"));
        checkOut25.setWidth(11);
        checkOut25.setX(389);
        checkOut25.setY(316);
        element3.addBasicElement(checkOut25);
        checkOut25.onAttributesInitialized();
        checkOut25.onChildrenAdded();
        final PixmapElement checkOut26 = PixmapElement.checkOut();
        checkOut26.setElementMap(elementMap);
        checkOut26.setHeight(28);
        checkOut26.setPosition(Alignment17.EAST);
        checkOut26.setRotation(GeometrySprite.SpriteRotation.QUARTER_COUNTER_CLOCKWISE);
        checkOut26.setWidth(0);
        checkOut26.setX(214);
        checkOut26.setY(434);
        element3.addBasicElement(checkOut26);
        checkOut26.onAttributesInitialized();
        checkOut26.onChildrenAdded();
        final PixmapElement checkOut27 = PixmapElement.checkOut();
        checkOut27.setElementMap(elementMap);
        checkOut27.setHeight(28);
        checkOut27.setPosition(Alignment17.SOUTH_EAST);
        checkOut27.setRotation(GeometrySprite.SpriteRotation.QUARTER_COUNTER_CLOCKWISE);
        checkOut27.setTexture(this.doc.getTexture("default_0.tga"));
        checkOut27.setWidth(11);
        checkOut27.setX(307);
        checkOut27.setY(380);
        element3.addBasicElement(checkOut27);
        checkOut27.onAttributesInitialized();
        checkOut27.onChildrenAdded();
        final PixmapElement checkOut28 = PixmapElement.checkOut();
        checkOut28.setElementMap(elementMap);
        checkOut28.setHeight(1);
        checkOut28.setPosition(Alignment17.SOUTH);
        checkOut28.setRotation(GeometrySprite.SpriteRotation.QUARTER_COUNTER_CLOCKWISE);
        checkOut28.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut28.setWidth(11);
        checkOut28.setX(502);
        checkOut28.setY(142);
        element3.addBasicElement(checkOut28);
        checkOut28.onAttributesInitialized();
        checkOut28.onChildrenAdded();
        element3.onChildrenAdded();
        final PixmapBackground checkOut29 = PixmapBackground.checkOut();
        checkOut29.setElementMap(elementMap);
        checkOut29.setEnabled(true);
        checkOut29.setScaled(true);
        appearance3.addBasicElement(checkOut29);
        checkOut29.onAttributesInitialized();
        final PixmapElement checkOut30 = PixmapElement.checkOut();
        checkOut30.setElementMap(elementMap);
        checkOut30.setHeight(1);
        checkOut30.setPosition(Alignment17.CENTER);
        checkOut30.setRotation(GeometrySprite.SpriteRotation.QUARTER_COUNTER_CLOCKWISE);
        checkOut30.setWidth(0);
        checkOut30.setX(214);
        checkOut30.setY(433);
        checkOut29.addBasicElement(checkOut30);
        checkOut30.onAttributesInitialized();
        checkOut30.onChildrenAdded();
        checkOut29.onChildrenAdded();
        appearance3.onChildrenAdded();
    }
}
