package com.ankamagames.wakfu.client.ui.theme;

import java.util.*;
import com.ankamagames.xulor2.component.*;
import com.ankamagames.xulor2.core.*;
import com.ankamagames.framework.graphics.image.*;
import com.ankamagames.xulor2.appearance.spacing.*;
import java.awt.*;
import com.ankamagames.xulor2.util.alignment.*;
import com.ankamagames.framework.graphics.engine.geometry.*;
import com.ankamagames.xulor2.decorator.*;
import com.ankamagames.xulor2.appearance.*;

public class Table implements StyleSetter
{
    private DocumentParser doc;
    private Stack<ElementMap> elementMaps;
    
    public Table() {
        super();
        this.elementMaps = new Stack<ElementMap>();
    }
    
    @Override
    public void applyStyle(final ElementMap item, final DocumentParser doc, final Widget widget) {
        this.doc = doc;
        this.elementMaps.push(item);
        final ElementMap elementMap = this.elementMaps.peek();
        final DecoratorAppearance appearance = widget.getAppearance();
        appearance.setElementMap(elementMap);
        widget.addBasicElement(appearance);
        appearance.onAttributesInitialized();
        final ColorElement checkOut = ColorElement.checkOut();
        checkOut.setElementMap(elementMap);
        checkOut.setColor(new Color(1.0f, 1.0f, 1.0f, 0.5f));
        checkOut.setName("mouseOverCell");
        appearance.addBasicElement(checkOut);
        checkOut.onAttributesInitialized();
        checkOut.onChildrenAdded();
        final ColorElement checkOut2 = ColorElement.checkOut();
        checkOut2.setElementMap(elementMap);
        checkOut2.setColor(new Color(0.64f, 0.7f, 0.7f, 1.0f));
        checkOut2.setName("selected");
        appearance.addBasicElement(checkOut2);
        checkOut2.onAttributesInitialized();
        checkOut2.onChildrenAdded();
        final ColorElement checkOut3 = ColorElement.checkOut();
        checkOut3.setElementMap(elementMap);
        checkOut3.setColor(new Color(0.37f, 0.44f, 0.43f, 1.0f));
        checkOut3.setName("evenCell");
        appearance.addBasicElement(checkOut3);
        checkOut3.onAttributesInitialized();
        checkOut3.onChildrenAdded();
        final ColorElement checkOut4 = ColorElement.checkOut();
        checkOut4.setElementMap(elementMap);
        checkOut4.setColor(new Color(0.45f, 0.52f, 0.51f, 1.0f));
        checkOut4.setName("oddCell");
        appearance.addBasicElement(checkOut4);
        checkOut4.onAttributesInitialized();
        checkOut4.onChildrenAdded();
        final Widget widgetByThemeElementName = appearance.getParentOfType(Widget.class).getWidgetByThemeElementName("scrollBar", false);
        if (widgetByThemeElementName != null) {
            final DecoratorAppearance appearance2 = widgetByThemeElementName.getAppearance();
            appearance2.setElementMap(elementMap);
            widgetByThemeElementName.addBasicElement(appearance2);
            appearance2.onAttributesInitialized();
            final Widget widgetByThemeElementName2 = appearance2.getParentOfType(Widget.class).getWidgetByThemeElementName("verticalIncreaseButton", false);
            if (widgetByThemeElementName2 != null) {
                final Padding element = new Padding();
                element.onCheckOut();
                element.setElementMap(elementMap);
                element.setInsets(new Insets(3, 0, 3, 0));
                widgetByThemeElementName2.addBasicElement(element);
                element.onAttributesInitialized();
                element.onChildrenAdded();
                final DecoratorAppearance appearance3 = widgetByThemeElementName2.getAppearance();
                appearance3.setElementMap(elementMap);
                ((TextWidgetAppearance)appearance3).setAlignment(Alignment9.CENTER);
                appearance3.setState("default");
                widgetByThemeElementName2.addBasicElement(appearance3);
                appearance3.onAttributesInitialized();
                final PixmapElement checkOut5 = PixmapElement.checkOut();
                checkOut5.setElementMap(elementMap);
                checkOut5.setHeight(18);
                checkOut5.setPosition(Alignment17.CENTER);
                checkOut5.setRotation(GeometrySprite.SpriteRotation.QUARTER_CLOCKWISE);
                checkOut5.setTexture(this.doc.getTexture("default_1.tga"));
                checkOut5.setWidth(16);
                checkOut5.setX(215);
                checkOut5.setY(744);
                appearance3.addBasicElement(checkOut5);
                checkOut5.onAttributesInitialized();
                checkOut5.onChildrenAdded();
                appearance3.onChildrenAdded();
                final DecoratorAppearance appearance4 = widgetByThemeElementName2.getAppearance();
                appearance4.setElementMap(elementMap);
                ((TextWidgetAppearance)appearance4).setAlignment(Alignment9.CENTER);
                appearance4.setState("mouseHover");
                widgetByThemeElementName2.addBasicElement(appearance4);
                appearance4.onAttributesInitialized();
                final PixmapElement checkOut6 = PixmapElement.checkOut();
                checkOut6.setElementMap(elementMap);
                checkOut6.setHeight(18);
                checkOut6.setPosition(Alignment17.CENTER);
                checkOut6.setRotation(GeometrySprite.SpriteRotation.QUARTER_CLOCKWISE);
                checkOut6.setTexture(this.doc.getTexture("default_0.tga"));
                checkOut6.setWidth(16);
                checkOut6.setX(964);
                checkOut6.setY(14);
                appearance4.addBasicElement(checkOut6);
                checkOut6.onAttributesInitialized();
                checkOut6.onChildrenAdded();
                appearance4.onChildrenAdded();
                final DecoratorAppearance appearance5 = widgetByThemeElementName2.getAppearance();
                appearance5.setElementMap(elementMap);
                ((TextWidgetAppearance)appearance5).setAlignment(Alignment9.CENTER);
                appearance5.setState("pressed");
                widgetByThemeElementName2.addBasicElement(appearance5);
                appearance5.onAttributesInitialized();
                final PixmapElement checkOut7 = PixmapElement.checkOut();
                checkOut7.setElementMap(elementMap);
                checkOut7.setHeight(18);
                checkOut7.setPosition(Alignment17.CENTER);
                checkOut7.setRotation(GeometrySprite.SpriteRotation.QUARTER_CLOCKWISE);
                checkOut7.setTexture(this.doc.getTexture("default_1.tga"));
                checkOut7.setWidth(16);
                checkOut7.setX(215);
                checkOut7.setY(723);
                appearance5.addBasicElement(checkOut7);
                checkOut7.onAttributesInitialized();
                checkOut7.onChildrenAdded();
                appearance5.onChildrenAdded();
            }
            final Widget widgetByThemeElementName3 = appearance2.getParentOfType(Widget.class).getWidgetByThemeElementName("verticalDecreaseButton", false);
            if (widgetByThemeElementName3 != null) {
                final Padding element2 = new Padding();
                element2.onCheckOut();
                element2.setElementMap(elementMap);
                element2.setInsets(new Insets(3, 0, 3, 0));
                widgetByThemeElementName3.addBasicElement(element2);
                element2.onAttributesInitialized();
                element2.onChildrenAdded();
                final DecoratorAppearance appearance6 = widgetByThemeElementName3.getAppearance();
                appearance6.setElementMap(elementMap);
                ((TextWidgetAppearance)appearance6).setAlignment(Alignment9.CENTER);
                appearance6.setState("default");
                widgetByThemeElementName3.addBasicElement(appearance6);
                appearance6.onAttributesInitialized();
                final PixmapElement checkOut8 = PixmapElement.checkOut();
                checkOut8.setElementMap(elementMap);
                checkOut8.setHeight(18);
                checkOut8.setPosition(Alignment17.CENTER);
                checkOut8.setRotation(GeometrySprite.SpriteRotation.QUARTER_COUNTER_CLOCKWISE);
                checkOut8.setTexture(this.doc.getTexture("default_1.tga"));
                checkOut8.setWidth(16);
                checkOut8.setX(215);
                checkOut8.setY(744);
                appearance6.addBasicElement(checkOut8);
                checkOut8.onAttributesInitialized();
                checkOut8.onChildrenAdded();
                appearance6.onChildrenAdded();
                final DecoratorAppearance appearance7 = widgetByThemeElementName3.getAppearance();
                appearance7.setElementMap(elementMap);
                ((TextWidgetAppearance)appearance7).setAlignment(Alignment9.CENTER);
                appearance7.setState("mouseHover");
                widgetByThemeElementName3.addBasicElement(appearance7);
                appearance7.onAttributesInitialized();
                final PixmapElement checkOut9 = PixmapElement.checkOut();
                checkOut9.setElementMap(elementMap);
                checkOut9.setHeight(18);
                checkOut9.setPosition(Alignment17.CENTER);
                checkOut9.setRotation(GeometrySprite.SpriteRotation.QUARTER_COUNTER_CLOCKWISE);
                checkOut9.setTexture(this.doc.getTexture("default_0.tga"));
                checkOut9.setWidth(16);
                checkOut9.setX(964);
                checkOut9.setY(14);
                appearance7.addBasicElement(checkOut9);
                checkOut9.onAttributesInitialized();
                checkOut9.onChildrenAdded();
                appearance7.onChildrenAdded();
                final DecoratorAppearance appearance8 = widgetByThemeElementName3.getAppearance();
                appearance8.setElementMap(elementMap);
                ((TextWidgetAppearance)appearance8).setAlignment(Alignment9.CENTER);
                appearance8.setState("pressed");
                widgetByThemeElementName3.addBasicElement(appearance8);
                appearance8.onAttributesInitialized();
                final PixmapElement checkOut10 = PixmapElement.checkOut();
                checkOut10.setElementMap(elementMap);
                checkOut10.setHeight(18);
                checkOut10.setPosition(Alignment17.CENTER);
                checkOut10.setRotation(GeometrySprite.SpriteRotation.QUARTER_COUNTER_CLOCKWISE);
                checkOut10.setTexture(this.doc.getTexture("default_1.tga"));
                checkOut10.setWidth(16);
                checkOut10.setX(215);
                checkOut10.setY(723);
                appearance8.addBasicElement(checkOut10);
                checkOut10.onAttributesInitialized();
                checkOut10.onChildrenAdded();
                appearance8.onChildrenAdded();
            }
            final Widget widgetByThemeElementName4 = appearance2.getParentOfType(Widget.class).getWidgetByThemeElementName("verticalSlider", false);
            if (widgetByThemeElementName4 != null) {
                final DecoratorAppearance appearance9 = widgetByThemeElementName4.getAppearance();
                appearance9.setElementMap(elementMap);
                widgetByThemeElementName4.addBasicElement(appearance9);
                appearance9.onAttributesInitialized();
                final Padding element3 = new Padding();
                element3.onCheckOut();
                element3.setElementMap(elementMap);
                element3.setInsets(new Insets(0, 4, 0, 4));
                appearance9.addBasicElement(element3);
                element3.onAttributesInitialized();
                element3.onChildrenAdded();
                final Widget widgetByThemeElementName5 = appearance9.getParentOfType(Widget.class).getWidgetByThemeElementName("verticalButton", false);
                if (widgetByThemeElementName5 != null) {
                    final DecoratorAppearance appearance10 = widgetByThemeElementName5.getAppearance();
                    appearance10.setElementMap(elementMap);
                    appearance10.setState("default");
                    widgetByThemeElementName5.addBasicElement(appearance10);
                    appearance10.onAttributesInitialized();
                    final PixmapBorder element4 = new PixmapBorder();
                    element4.onCheckOut();
                    element4.setElementMap(elementMap);
                    appearance10.addBasicElement(element4);
                    element4.onAttributesInitialized();
                    final PixmapElement checkOut11 = PixmapElement.checkOut();
                    checkOut11.setElementMap(elementMap);
                    checkOut11.setHeight(4);
                    checkOut11.setPosition(Alignment17.NORTH_WEST);
                    checkOut11.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut11.setWidth(1);
                    checkOut11.setX(540);
                    checkOut11.setY(286);
                    element4.addBasicElement(checkOut11);
                    checkOut11.onAttributesInitialized();
                    checkOut11.onChildrenAdded();
                    final PixmapElement checkOut12 = PixmapElement.checkOut();
                    checkOut12.setElementMap(elementMap);
                    checkOut12.setHeight(4);
                    checkOut12.setPosition(Alignment17.NORTH);
                    checkOut12.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut12.setWidth(11);
                    checkOut12.setX(146);
                    checkOut12.setY(239);
                    element4.addBasicElement(checkOut12);
                    checkOut12.onAttributesInitialized();
                    checkOut12.onChildrenAdded();
                    final PixmapElement checkOut13 = PixmapElement.checkOut();
                    checkOut13.setElementMap(elementMap);
                    checkOut13.setHeight(4);
                    checkOut13.setPosition(Alignment17.NORTH_EAST);
                    checkOut13.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut13.setWidth(1);
                    checkOut13.setX(594);
                    checkOut13.setY(286);
                    element4.addBasicElement(checkOut13);
                    checkOut13.onAttributesInitialized();
                    checkOut13.onChildrenAdded();
                    final PixmapElement checkOut14 = PixmapElement.checkOut();
                    checkOut14.setElementMap(elementMap);
                    checkOut14.setHeight(13);
                    checkOut14.setPosition(Alignment17.EAST);
                    checkOut14.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut14.setWidth(1);
                    checkOut14.setX(827);
                    checkOut14.setY(753);
                    element4.addBasicElement(checkOut14);
                    checkOut14.onAttributesInitialized();
                    checkOut14.onChildrenAdded();
                    final PixmapElement checkOut15 = PixmapElement.checkOut();
                    checkOut15.setElementMap(elementMap);
                    checkOut15.setHeight(4);
                    checkOut15.setPosition(Alignment17.SOUTH_EAST);
                    checkOut15.setTexture(this.doc.getTexture("default_0.tga"));
                    checkOut15.setWidth(1);
                    checkOut15.setX(315);
                    checkOut15.setY(474);
                    element4.addBasicElement(checkOut15);
                    checkOut15.onAttributesInitialized();
                    checkOut15.onChildrenAdded();
                    final PixmapElement checkOut16 = PixmapElement.checkOut();
                    checkOut16.setElementMap(elementMap);
                    checkOut16.setHeight(4);
                    checkOut16.setPosition(Alignment17.SOUTH);
                    checkOut16.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut16.setWidth(11);
                    checkOut16.setX(282);
                    checkOut16.setY(283);
                    element4.addBasicElement(checkOut16);
                    checkOut16.onAttributesInitialized();
                    checkOut16.onChildrenAdded();
                    final PixmapElement checkOut17 = PixmapElement.checkOut();
                    checkOut17.setElementMap(elementMap);
                    checkOut17.setHeight(4);
                    checkOut17.setPosition(Alignment17.SOUTH_WEST);
                    checkOut17.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut17.setWidth(1);
                    checkOut17.setX(594);
                    checkOut17.setY(286);
                    element4.addBasicElement(checkOut17);
                    checkOut17.onAttributesInitialized();
                    checkOut17.onChildrenAdded();
                    final PixmapElement checkOut18 = PixmapElement.checkOut();
                    checkOut18.setElementMap(elementMap);
                    checkOut18.setHeight(13);
                    checkOut18.setPosition(Alignment17.WEST);
                    checkOut18.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut18.setWidth(1);
                    checkOut18.setX(827);
                    checkOut18.setY(753);
                    element4.addBasicElement(checkOut18);
                    checkOut18.onAttributesInitialized();
                    checkOut18.onChildrenAdded();
                    element4.onChildrenAdded();
                    final PixmapBackground checkOut19 = PixmapBackground.checkOut();
                    checkOut19.setElementMap(elementMap);
                    checkOut19.setEnabled(true);
                    checkOut19.setScaled(true);
                    appearance10.addBasicElement(checkOut19);
                    checkOut19.onAttributesInitialized();
                    final PixmapElement checkOut20 = PixmapElement.checkOut();
                    checkOut20.setElementMap(elementMap);
                    checkOut20.setHeight(2);
                    checkOut20.setPosition(Alignment17.CENTER);
                    checkOut20.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut20.setWidth(11);
                    checkOut20.setX(829);
                    checkOut20.setY(283);
                    checkOut19.addBasicElement(checkOut20);
                    checkOut20.onAttributesInitialized();
                    checkOut20.onChildrenAdded();
                    checkOut19.onChildrenAdded();
                    final PixmapElement checkOut21 = PixmapElement.checkOut();
                    checkOut21.setElementMap(elementMap);
                    checkOut21.setHeight(5);
                    checkOut21.setPosition(Alignment17.CENTER);
                    checkOut21.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut21.setWidth(11);
                    checkOut21.setX(594);
                    checkOut21.setY(669);
                    appearance10.addBasicElement(checkOut21);
                    checkOut21.onAttributesInitialized();
                    checkOut21.onChildrenAdded();
                    appearance10.onChildrenAdded();
                    final DecoratorAppearance appearance11 = widgetByThemeElementName5.getAppearance();
                    appearance11.setElementMap(elementMap);
                    appearance11.setState("mouseHover");
                    widgetByThemeElementName5.addBasicElement(appearance11);
                    appearance11.onAttributesInitialized();
                    final PixmapBorder element5 = new PixmapBorder();
                    element5.onCheckOut();
                    element5.setElementMap(elementMap);
                    element5.setEnabled(false);
                    appearance11.addBasicElement(element5);
                    element5.onAttributesInitialized();
                    final PixmapElement checkOut22 = PixmapElement.checkOut();
                    checkOut22.setElementMap(elementMap);
                    checkOut22.setHeight(4);
                    checkOut22.setPosition(Alignment17.NORTH_WEST);
                    checkOut22.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut22.setWidth(1);
                    checkOut22.setX(321);
                    checkOut22.setY(278);
                    element5.addBasicElement(checkOut22);
                    checkOut22.onAttributesInitialized();
                    checkOut22.onChildrenAdded();
                    final PixmapElement checkOut23 = PixmapElement.checkOut();
                    checkOut23.setElementMap(elementMap);
                    checkOut23.setHeight(4);
                    checkOut23.setPosition(Alignment17.NORTH);
                    checkOut23.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut23.setWidth(11);
                    checkOut23.setX(185);
                    checkOut23.setY(283);
                    element5.addBasicElement(checkOut23);
                    checkOut23.onAttributesInitialized();
                    checkOut23.onChildrenAdded();
                    final PixmapElement checkOut24 = PixmapElement.checkOut();
                    checkOut24.setElementMap(elementMap);
                    checkOut24.setHeight(4);
                    checkOut24.setPosition(Alignment17.NORTH_EAST);
                    checkOut24.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut24.setWidth(1);
                    checkOut24.setX(594);
                    checkOut24.setY(286);
                    element5.addBasicElement(checkOut24);
                    checkOut24.onAttributesInitialized();
                    checkOut24.onChildrenAdded();
                    final PixmapElement checkOut25 = PixmapElement.checkOut();
                    checkOut25.setElementMap(elementMap);
                    checkOut25.setHeight(13);
                    checkOut25.setPosition(Alignment17.EAST);
                    checkOut25.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut25.setWidth(1);
                    checkOut25.setX(397);
                    checkOut25.setY(718);
                    element5.addBasicElement(checkOut25);
                    checkOut25.onAttributesInitialized();
                    checkOut25.onChildrenAdded();
                    final PixmapElement checkOut26 = PixmapElement.checkOut();
                    checkOut26.setElementMap(elementMap);
                    checkOut26.setHeight(4);
                    checkOut26.setPosition(Alignment17.SOUTH_EAST);
                    checkOut26.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut26.setWidth(1);
                    checkOut26.setX(294);
                    checkOut26.setY(330);
                    element5.addBasicElement(checkOut26);
                    checkOut26.onAttributesInitialized();
                    checkOut26.onChildrenAdded();
                    final PixmapElement checkOut27 = PixmapElement.checkOut();
                    checkOut27.setElementMap(elementMap);
                    checkOut27.setHeight(4);
                    checkOut27.setPosition(Alignment17.SOUTH);
                    checkOut27.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut27.setWidth(11);
                    checkOut27.setX(595);
                    checkOut27.setY(586);
                    element5.addBasicElement(checkOut27);
                    checkOut27.onAttributesInitialized();
                    checkOut27.onChildrenAdded();
                    final PixmapElement checkOut28 = PixmapElement.checkOut();
                    checkOut28.setElementMap(elementMap);
                    checkOut28.setHeight(4);
                    checkOut28.setPosition(Alignment17.SOUTH_WEST);
                    checkOut28.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut28.setWidth(1);
                    checkOut28.setX(594);
                    checkOut28.setY(286);
                    element5.addBasicElement(checkOut28);
                    checkOut28.onAttributesInitialized();
                    checkOut28.onChildrenAdded();
                    final PixmapElement checkOut29 = PixmapElement.checkOut();
                    checkOut29.setElementMap(elementMap);
                    checkOut29.setHeight(13);
                    checkOut29.setPosition(Alignment17.WEST);
                    checkOut29.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut29.setWidth(1);
                    checkOut29.setX(397);
                    checkOut29.setY(718);
                    element5.addBasicElement(checkOut29);
                    checkOut29.onAttributesInitialized();
                    checkOut29.onChildrenAdded();
                    element5.onChildrenAdded();
                    final PixmapBackground checkOut30 = PixmapBackground.checkOut();
                    checkOut30.setElementMap(elementMap);
                    checkOut30.setEnabled(false);
                    checkOut30.setScaled(true);
                    appearance11.addBasicElement(checkOut30);
                    checkOut30.onAttributesInitialized();
                    final PixmapElement checkOut31 = PixmapElement.checkOut();
                    checkOut31.setElementMap(elementMap);
                    checkOut31.setHeight(2);
                    checkOut31.setPosition(Alignment17.CENTER);
                    checkOut31.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut31.setWidth(11);
                    checkOut31.setX(800);
                    checkOut31.setY(199);
                    checkOut30.addBasicElement(checkOut31);
                    checkOut31.onAttributesInitialized();
                    checkOut31.onChildrenAdded();
                    checkOut30.onChildrenAdded();
                    final PixmapElement checkOut32 = PixmapElement.checkOut();
                    checkOut32.setElementMap(elementMap);
                    checkOut32.setHeight(5);
                    checkOut32.setPosition(Alignment17.CENTER);
                    checkOut32.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut32.setWidth(11);
                    checkOut32.setX(968);
                    checkOut32.setY(330);
                    appearance11.addBasicElement(checkOut32);
                    checkOut32.onAttributesInitialized();
                    checkOut32.onChildrenAdded();
                    appearance11.onChildrenAdded();
                    final DecoratorAppearance appearance12 = widgetByThemeElementName5.getAppearance();
                    appearance12.setElementMap(elementMap);
                    appearance12.setState("pressed");
                    widgetByThemeElementName5.addBasicElement(appearance12);
                    appearance12.onAttributesInitialized();
                    final PixmapBorder element6 = new PixmapBorder();
                    element6.onCheckOut();
                    element6.setElementMap(elementMap);
                    element6.setEnabled(false);
                    appearance12.addBasicElement(element6);
                    element6.onAttributesInitialized();
                    final PixmapElement checkOut33 = PixmapElement.checkOut();
                    checkOut33.setElementMap(elementMap);
                    checkOut33.setHeight(4);
                    checkOut33.setPosition(Alignment17.NORTH_WEST);
                    checkOut33.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut33.setWidth(1);
                    checkOut33.setX(255);
                    checkOut33.setY(292);
                    element6.addBasicElement(checkOut33);
                    checkOut33.onAttributesInitialized();
                    checkOut33.onChildrenAdded();
                    final PixmapElement checkOut34 = PixmapElement.checkOut();
                    checkOut34.setElementMap(elementMap);
                    checkOut34.setHeight(4);
                    checkOut34.setPosition(Alignment17.NORTH);
                    checkOut34.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut34.setWidth(11);
                    checkOut34.setX(280);
                    checkOut34.setY(330);
                    element6.addBasicElement(checkOut34);
                    checkOut34.onAttributesInitialized();
                    checkOut34.onChildrenAdded();
                    final PixmapElement checkOut35 = PixmapElement.checkOut();
                    checkOut35.setElementMap(elementMap);
                    checkOut35.setHeight(4);
                    checkOut35.setPosition(Alignment17.NORTH_EAST);
                    checkOut35.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut35.setWidth(1);
                    checkOut35.setX(594);
                    checkOut35.setY(286);
                    element6.addBasicElement(checkOut35);
                    checkOut35.onAttributesInitialized();
                    checkOut35.onChildrenAdded();
                    this.method0(element6);
                    this.method1(element6);
                    this.method2(element6);
                    this.method3(element6);
                    this.method4(element6);
                    element6.onChildrenAdded();
                    this.method5(appearance12);
                    this.method6(appearance12);
                    appearance12.onChildrenAdded();
                }
                appearance9.onChildrenAdded();
            }
            appearance2.onChildrenAdded();
        }
        appearance.onChildrenAdded();
    }
    
    public BasicElement method0(final BasicElement basicElement) {
        final ElementMap elementMap = this.elementMaps.peek();
        final PixmapElement checkOut = PixmapElement.checkOut();
        checkOut.setElementMap(elementMap);
        checkOut.setHeight(13);
        checkOut.setPosition(Alignment17.EAST);
        checkOut.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut.setWidth(1);
        checkOut.setX(397);
        checkOut.setY(766);
        basicElement.addBasicElement(checkOut);
        checkOut.onAttributesInitialized();
        checkOut.onChildrenAdded();
        return checkOut;
    }
    
    public BasicElement method1(final BasicElement basicElement) {
        final ElementMap elementMap = this.elementMaps.peek();
        final PixmapElement checkOut = PixmapElement.checkOut();
        checkOut.setElementMap(elementMap);
        checkOut.setHeight(4);
        checkOut.setPosition(Alignment17.SOUTH_EAST);
        checkOut.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut.setWidth(1);
        checkOut.setX(628);
        checkOut.setY(276);
        basicElement.addBasicElement(checkOut);
        checkOut.onAttributesInitialized();
        checkOut.onChildrenAdded();
        return checkOut;
    }
    
    public BasicElement method2(final BasicElement basicElement) {
        final ElementMap elementMap = this.elementMaps.peek();
        final PixmapElement checkOut = PixmapElement.checkOut();
        checkOut.setElementMap(elementMap);
        checkOut.setHeight(4);
        checkOut.setPosition(Alignment17.SOUTH);
        checkOut.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut.setWidth(11);
        checkOut.setX(920);
        checkOut.setY(587);
        basicElement.addBasicElement(checkOut);
        checkOut.onAttributesInitialized();
        checkOut.onChildrenAdded();
        return checkOut;
    }
    
    public BasicElement method3(final BasicElement basicElement) {
        final ElementMap elementMap = this.elementMaps.peek();
        final PixmapElement checkOut = PixmapElement.checkOut();
        checkOut.setElementMap(elementMap);
        checkOut.setHeight(4);
        checkOut.setPosition(Alignment17.SOUTH_WEST);
        checkOut.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut.setWidth(1);
        checkOut.setX(594);
        checkOut.setY(286);
        basicElement.addBasicElement(checkOut);
        checkOut.onAttributesInitialized();
        checkOut.onChildrenAdded();
        return checkOut;
    }
    
    public BasicElement method4(final BasicElement basicElement) {
        final ElementMap elementMap = this.elementMaps.peek();
        final PixmapElement checkOut = PixmapElement.checkOut();
        checkOut.setElementMap(elementMap);
        checkOut.setHeight(13);
        checkOut.setPosition(Alignment17.WEST);
        checkOut.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut.setWidth(1);
        checkOut.setX(397);
        checkOut.setY(766);
        basicElement.addBasicElement(checkOut);
        checkOut.onAttributesInitialized();
        checkOut.onChildrenAdded();
        return checkOut;
    }
    
    public BasicElement method5(final BasicElement basicElement) {
        final ElementMap elementMap = this.elementMaps.peek();
        final PixmapBackground checkOut = PixmapBackground.checkOut();
        checkOut.setElementMap(elementMap);
        checkOut.setEnabled(false);
        checkOut.setScaled(true);
        basicElement.addBasicElement(checkOut);
        checkOut.onAttributesInitialized();
        final PixmapElement checkOut2 = PixmapElement.checkOut();
        checkOut2.setElementMap(elementMap);
        checkOut2.setHeight(2);
        checkOut2.setPosition(Alignment17.CENTER);
        checkOut2.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut2.setWidth(11);
        checkOut2.setX(379);
        checkOut2.setY(239);
        checkOut.addBasicElement(checkOut2);
        checkOut2.onAttributesInitialized();
        checkOut2.onChildrenAdded();
        checkOut.onChildrenAdded();
        return checkOut;
    }
    
    public BasicElement method6(final BasicElement basicElement) {
        final ElementMap elementMap = this.elementMaps.peek();
        final PixmapElement checkOut = PixmapElement.checkOut();
        checkOut.setElementMap(elementMap);
        checkOut.setHeight(5);
        checkOut.setPosition(Alignment17.CENTER);
        checkOut.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut.setWidth(11);
        checkOut.setX(361);
        checkOut.setY(549);
        basicElement.addBasicElement(checkOut);
        checkOut.onAttributesInitialized();
        checkOut.onChildrenAdded();
        return checkOut;
    }
}
