package com.ankamagames.wakfu.client.ui.theme;

import java.util.*;
import com.ankamagames.xulor2.component.*;
import com.ankamagames.framework.graphics.image.*;
import com.ankamagames.xulor2.*;
import com.ankamagames.xulor2.core.*;
import com.ankamagames.xulor2.util.alignment.*;
import com.ankamagames.xulor2.decorator.*;
import com.ankamagames.xulor2.appearance.*;

public class TablePremium$Button implements StyleSetter
{
    private DocumentParser doc;
    private Stack<ElementMap> elementMaps;
    
    public TablePremium$Button() {
        super();
        this.elementMaps = new Stack<ElementMap>();
    }
    
    @Override
    public void applyStyle(final ElementMap item, final DocumentParser doc, final Widget widget) {
        this.doc = doc;
        this.elementMaps.push(item);
        final ElementMap elementMap = this.elementMaps.peek();
        final DecoratorAppearance appearance = widget.getAppearance();
        appearance.setElementMap(elementMap);
        appearance.setModulationColor(new Color(0.827451f, 0.58431375f, 0.0f, 1.0f));
        appearance.setState("default");
        widget.addBasicElement(appearance);
        appearance.onAttributesInitialized();
        final FontElement checkOut = FontElement.checkOut();
        checkOut.setRenderer(Xulor.getInstance().getDocumentParser().getFont("defaultBoldFont"));
        checkOut.setElementMap(elementMap);
        appearance.addBasicElement(checkOut);
        checkOut.onAttributesInitialized();
        checkOut.onChildrenAdded();
        final String id = "defaultLightColor";
        final ColorElement checkOut2 = ColorElement.checkOut();
        checkOut2.setElementMap(elementMap);
        if (elementMap != null && id != null) {
            elementMap.add(id, checkOut2);
        }
        checkOut2.setColor(new Color(1.0f, 1.0f, 1.0f, 1.0f));
        appearance.addBasicElement(checkOut2);
        checkOut2.onAttributesInitialized();
        checkOut2.onChildrenAdded();
        final String id2 = "buttonFlatBackgroundDefault";
        final PixmapBackground checkOut3 = PixmapBackground.checkOut();
        checkOut3.setElementMap(elementMap);
        if (elementMap != null && id2 != null) {
            elementMap.add(id2, checkOut3);
        }
        checkOut3.setScaled(true);
        appearance.addBasicElement(checkOut3);
        checkOut3.onAttributesInitialized();
        final PixmapElement checkOut4 = PixmapElement.checkOut();
        checkOut4.setElementMap(elementMap);
        checkOut4.setHeight(7);
        checkOut4.setPosition(Alignment17.CENTER);
        checkOut4.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut4.setWidth(1);
        checkOut4.setX(522);
        checkOut4.setY(504);
        checkOut3.addBasicElement(checkOut4);
        checkOut4.onAttributesInitialized();
        checkOut4.onChildrenAdded();
        checkOut3.onChildrenAdded();
        final String id3 = "buttonFlatBorderDefault";
        final PixmapBorder pixmapBorder = new PixmapBorder();
        pixmapBorder.onCheckOut();
        pixmapBorder.setElementMap(elementMap);
        if (elementMap != null && id3 != null) {
            elementMap.add(id3, pixmapBorder);
        }
        appearance.addBasicElement(pixmapBorder);
        pixmapBorder.onAttributesInitialized();
        final PixmapElement checkOut5 = PixmapElement.checkOut();
        checkOut5.setElementMap(elementMap);
        checkOut5.setHeight(3);
        checkOut5.setPosition(Alignment17.NORTH_WEST);
        checkOut5.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut5.setWidth(3);
        checkOut5.setX(626);
        checkOut5.setY(233);
        pixmapBorder.addBasicElement(checkOut5);
        checkOut5.onAttributesInitialized();
        checkOut5.onChildrenAdded();
        final PixmapElement checkOut6 = PixmapElement.checkOut();
        checkOut6.setElementMap(elementMap);
        checkOut6.setHeight(3);
        checkOut6.setPosition(Alignment17.NORTH);
        checkOut6.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut6.setWidth(1);
        checkOut6.setX(321);
        checkOut6.setY(254);
        pixmapBorder.addBasicElement(checkOut6);
        checkOut6.onAttributesInitialized();
        checkOut6.onChildrenAdded();
        final PixmapElement checkOut7 = PixmapElement.checkOut();
        checkOut7.setElementMap(elementMap);
        checkOut7.setHeight(3);
        checkOut7.setPosition(Alignment17.NORTH_EAST);
        checkOut7.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut7.setWidth(3);
        checkOut7.setX(509);
        checkOut7.setY(228);
        pixmapBorder.addBasicElement(checkOut7);
        checkOut7.onAttributesInitialized();
        checkOut7.onChildrenAdded();
        final PixmapElement checkOut8 = PixmapElement.checkOut();
        checkOut8.setElementMap(elementMap);
        checkOut8.setHeight(7);
        checkOut8.setPosition(Alignment17.WEST);
        checkOut8.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut8.setWidth(3);
        checkOut8.setX(229);
        checkOut8.setY(492);
        pixmapBorder.addBasicElement(checkOut8);
        checkOut8.onAttributesInitialized();
        checkOut8.onChildrenAdded();
        final PixmapElement checkOut9 = PixmapElement.checkOut();
        checkOut9.setElementMap(elementMap);
        checkOut9.setHeight(7);
        checkOut9.setPosition(Alignment17.EAST);
        checkOut9.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut9.setWidth(3);
        checkOut9.setX(1018);
        checkOut9.setY(502);
        pixmapBorder.addBasicElement(checkOut9);
        checkOut9.onAttributesInitialized();
        checkOut9.onChildrenAdded();
        final PixmapElement checkOut10 = PixmapElement.checkOut();
        checkOut10.setElementMap(elementMap);
        checkOut10.setHeight(3);
        checkOut10.setPosition(Alignment17.SOUTH_WEST);
        checkOut10.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut10.setWidth(3);
        checkOut10.setX(509);
        checkOut10.setY(234);
        pixmapBorder.addBasicElement(checkOut10);
        checkOut10.onAttributesInitialized();
        checkOut10.onChildrenAdded();
        final PixmapElement checkOut11 = PixmapElement.checkOut();
        checkOut11.setElementMap(elementMap);
        checkOut11.setHeight(3);
        checkOut11.setPosition(Alignment17.SOUTH);
        checkOut11.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut11.setWidth(1);
        checkOut11.setX(777);
        checkOut11.setY(356);
        pixmapBorder.addBasicElement(checkOut11);
        checkOut11.onAttributesInitialized();
        checkOut11.onChildrenAdded();
        final PixmapElement checkOut12 = PixmapElement.checkOut();
        checkOut12.setElementMap(elementMap);
        checkOut12.setHeight(3);
        checkOut12.setPosition(Alignment17.SOUTH_EAST);
        checkOut12.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut12.setWidth(3);
        checkOut12.setX(538);
        checkOut12.setY(331);
        pixmapBorder.addBasicElement(checkOut12);
        checkOut12.onAttributesInitialized();
        checkOut12.onChildrenAdded();
        pixmapBorder.onChildrenAdded();
        appearance.onChildrenAdded();
        final DecoratorAppearance appearance2 = widget.getAppearance();
        appearance2.setElementMap(elementMap);
        appearance2.setState("mouseHover");
        widget.addBasicElement(appearance2);
        appearance2.onAttributesInitialized();
        final String id4 = "buttonFlatBackgroundOver";
        final PixmapBackground checkOut13 = PixmapBackground.checkOut();
        checkOut13.setElementMap(elementMap);
        if (elementMap != null && id4 != null) {
            elementMap.add(id4, checkOut13);
        }
        checkOut13.setScaled(true);
        appearance2.addBasicElement(checkOut13);
        checkOut13.onAttributesInitialized();
        final PixmapElement checkOut14 = PixmapElement.checkOut();
        checkOut14.setElementMap(elementMap);
        checkOut14.setHeight(7);
        checkOut14.setPosition(Alignment17.CENTER);
        checkOut14.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut14.setWidth(1);
        checkOut14.setX(522);
        checkOut14.setY(504);
        checkOut13.addBasicElement(checkOut14);
        checkOut14.onAttributesInitialized();
        checkOut14.onChildrenAdded();
        checkOut13.onChildrenAdded();
        final String id5 = "buttonFlatBorderOver";
        final PixmapBorder pixmapBorder2 = new PixmapBorder();
        pixmapBorder2.onCheckOut();
        pixmapBorder2.setElementMap(elementMap);
        if (elementMap != null && id5 != null) {
            elementMap.add(id5, pixmapBorder2);
        }
        appearance2.addBasicElement(pixmapBorder2);
        pixmapBorder2.onAttributesInitialized();
        final PixmapElement checkOut15 = PixmapElement.checkOut();
        checkOut15.setElementMap(elementMap);
        checkOut15.setHeight(3);
        checkOut15.setPosition(Alignment17.NORTH_WEST);
        checkOut15.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut15.setWidth(3);
        checkOut15.setX(509);
        checkOut15.setY(222);
        pixmapBorder2.addBasicElement(checkOut15);
        checkOut15.onAttributesInitialized();
        checkOut15.onChildrenAdded();
        final PixmapElement checkOut16 = PixmapElement.checkOut();
        checkOut16.setElementMap(elementMap);
        checkOut16.setHeight(3);
        checkOut16.setPosition(Alignment17.NORTH);
        checkOut16.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut16.setWidth(1);
        checkOut16.setX(1019);
        checkOut16.setY(263);
        pixmapBorder2.addBasicElement(checkOut16);
        checkOut16.onAttributesInitialized();
        checkOut16.onChildrenAdded();
        final PixmapElement checkOut17 = PixmapElement.checkOut();
        checkOut17.setElementMap(elementMap);
        checkOut17.setHeight(3);
        checkOut17.setPosition(Alignment17.NORTH_EAST);
        checkOut17.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut17.setWidth(3);
        checkOut17.setX(1013);
        checkOut17.setY(263);
        pixmapBorder2.addBasicElement(checkOut17);
        checkOut17.onAttributesInitialized();
        checkOut17.onChildrenAdded();
        final PixmapElement checkOut18 = PixmapElement.checkOut();
        checkOut18.setElementMap(elementMap);
        checkOut18.setHeight(7);
        checkOut18.setPosition(Alignment17.WEST);
        checkOut18.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut18.setWidth(3);
        checkOut18.setX(229);
        checkOut18.setY(482);
        pixmapBorder2.addBasicElement(checkOut18);
        checkOut18.onAttributesInitialized();
        checkOut18.onChildrenAdded();
        final PixmapElement checkOut19 = PixmapElement.checkOut();
        checkOut19.setElementMap(elementMap);
        checkOut19.setHeight(7);
        checkOut19.setPosition(Alignment17.EAST);
        checkOut19.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut19.setWidth(3);
        checkOut19.setX(229);
        checkOut19.setY(502);
        pixmapBorder2.addBasicElement(checkOut19);
        checkOut19.onAttributesInitialized();
        checkOut19.onChildrenAdded();
        final PixmapElement checkOut20 = PixmapElement.checkOut();
        checkOut20.setElementMap(elementMap);
        checkOut20.setHeight(3);
        checkOut20.setPosition(Alignment17.SOUTH_WEST);
        checkOut20.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut20.setWidth(3);
        checkOut20.setX(111);
        checkOut20.setY(249);
        pixmapBorder2.addBasicElement(checkOut20);
        checkOut20.onAttributesInitialized();
        checkOut20.onChildrenAdded();
        final PixmapElement checkOut21 = PixmapElement.checkOut();
        checkOut21.setElementMap(elementMap);
        checkOut21.setHeight(3);
        checkOut21.setPosition(Alignment17.SOUTH);
        checkOut21.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut21.setWidth(1);
        checkOut21.setX(628);
        checkOut21.setY(264);
        pixmapBorder2.addBasicElement(checkOut21);
        checkOut21.onAttributesInitialized();
        checkOut21.onChildrenAdded();
        final PixmapElement checkOut22 = PixmapElement.checkOut();
        checkOut22.setElementMap(elementMap);
        checkOut22.setHeight(3);
        checkOut22.setPosition(Alignment17.SOUTH_EAST);
        checkOut22.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut22.setWidth(3);
        checkOut22.setX(626);
        checkOut22.setY(227);
        pixmapBorder2.addBasicElement(checkOut22);
        checkOut22.onAttributesInitialized();
        checkOut22.onChildrenAdded();
        pixmapBorder2.onChildrenAdded();
        appearance2.onChildrenAdded();
        final DecoratorAppearance appearance3 = widget.getAppearance();
        appearance3.setElementMap(elementMap);
        appearance3.setState("pressed");
        widget.addBasicElement(appearance3);
        appearance3.onAttributesInitialized();
        final String id6 = "buttonFlatBackgroundPressed";
        final PixmapBackground checkOut23 = PixmapBackground.checkOut();
        checkOut23.setElementMap(elementMap);
        if (elementMap != null && id6 != null) {
            elementMap.add(id6, checkOut23);
        }
        checkOut23.setScaled(true);
        appearance3.addBasicElement(checkOut23);
        checkOut23.onAttributesInitialized();
        final PixmapElement checkOut24 = PixmapElement.checkOut();
        checkOut24.setElementMap(elementMap);
        checkOut24.setHeight(7);
        checkOut24.setPosition(Alignment17.CENTER);
        checkOut24.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut24.setWidth(1);
        checkOut24.setX(88);
        checkOut24.setY(416);
        checkOut23.addBasicElement(checkOut24);
        checkOut24.onAttributesInitialized();
        checkOut24.onChildrenAdded();
        checkOut23.onChildrenAdded();
        final String id7 = "buttonFlatBorderPressed";
        final PixmapBorder pixmapBorder3 = new PixmapBorder();
        pixmapBorder3.onCheckOut();
        pixmapBorder3.setElementMap(elementMap);
        if (elementMap != null && id7 != null) {
            elementMap.add(id7, pixmapBorder3);
        }
        appearance3.addBasicElement(pixmapBorder3);
        pixmapBorder3.onAttributesInitialized();
        final PixmapElement checkOut25 = PixmapElement.checkOut();
        checkOut25.setElementMap(elementMap);
        checkOut25.setHeight(3);
        checkOut25.setPosition(Alignment17.NORTH_WEST);
        checkOut25.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut25.setWidth(3);
        checkOut25.setX(509);
        checkOut25.setY(222);
        pixmapBorder3.addBasicElement(checkOut25);
        checkOut25.onAttributesInitialized();
        checkOut25.onChildrenAdded();
        final PixmapElement checkOut26 = PixmapElement.checkOut();
        checkOut26.setElementMap(elementMap);
        checkOut26.setHeight(3);
        checkOut26.setPosition(Alignment17.NORTH);
        checkOut26.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut26.setWidth(1);
        checkOut26.setX(231);
        checkOut26.setY(356);
        pixmapBorder3.addBasicElement(checkOut26);
        checkOut26.onAttributesInitialized();
        checkOut26.onChildrenAdded();
        final PixmapElement checkOut27 = PixmapElement.checkOut();
        checkOut27.setElementMap(elementMap);
        checkOut27.setHeight(3);
        checkOut27.setPosition(Alignment17.NORTH_EAST);
        checkOut27.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut27.setWidth(3);
        checkOut27.setX(1013);
        checkOut27.setY(263);
        pixmapBorder3.addBasicElement(checkOut27);
        checkOut27.onAttributesInitialized();
        checkOut27.onChildrenAdded();
        final PixmapElement checkOut28 = PixmapElement.checkOut();
        checkOut28.setElementMap(elementMap);
        checkOut28.setHeight(7);
        checkOut28.setPosition(Alignment17.WEST);
        checkOut28.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut28.setWidth(3);
        checkOut28.setX(1018);
        checkOut28.setY(492);
        pixmapBorder3.addBasicElement(checkOut28);
        checkOut28.onAttributesInitialized();
        checkOut28.onChildrenAdded();
        final PixmapElement checkOut29 = PixmapElement.checkOut();
        checkOut29.setElementMap(elementMap);
        checkOut29.setHeight(7);
        checkOut29.setPosition(Alignment17.EAST);
        checkOut29.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut29.setWidth(3);
        checkOut29.setX(88);
        checkOut29.setY(528);
        pixmapBorder3.addBasicElement(checkOut29);
        checkOut29.onAttributesInitialized();
        checkOut29.onChildrenAdded();
        final PixmapElement checkOut30 = PixmapElement.checkOut();
        checkOut30.setElementMap(elementMap);
        checkOut30.setHeight(3);
        checkOut30.setPosition(Alignment17.SOUTH_WEST);
        checkOut30.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut30.setWidth(3);
        checkOut30.setX(111);
        checkOut30.setY(249);
        pixmapBorder3.addBasicElement(checkOut30);
        checkOut30.onAttributesInitialized();
        checkOut30.onChildrenAdded();
        final PixmapElement checkOut31 = PixmapElement.checkOut();
        checkOut31.setElementMap(elementMap);
        checkOut31.setHeight(3);
        checkOut31.setPosition(Alignment17.SOUTH);
        checkOut31.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut31.setWidth(1);
        checkOut31.setX(628);
        checkOut31.setY(270);
        pixmapBorder3.addBasicElement(checkOut31);
        checkOut31.onAttributesInitialized();
        checkOut31.onChildrenAdded();
        final PixmapElement checkOut32 = PixmapElement.checkOut();
        checkOut32.setElementMap(elementMap);
        checkOut32.setHeight(3);
        checkOut32.setPosition(Alignment17.SOUTH_EAST);
        checkOut32.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut32.setWidth(3);
        checkOut32.setX(626);
        checkOut32.setY(227);
        pixmapBorder3.addBasicElement(checkOut32);
        checkOut32.onAttributesInitialized();
        checkOut32.onChildrenAdded();
        pixmapBorder3.onChildrenAdded();
        appearance3.onChildrenAdded();
        final DecoratorAppearance appearance4 = widget.getAppearance();
        appearance4.setElementMap(elementMap);
        appearance4.setState("disabled");
        widget.addBasicElement(appearance4);
        appearance4.onAttributesInitialized();
        final String id8 = "buttonFlatBackgroundDisabled";
        final PixmapBackground checkOut33 = PixmapBackground.checkOut();
        checkOut33.setElementMap(elementMap);
        if (elementMap != null && id8 != null) {
            elementMap.add(id8, checkOut33);
        }
        checkOut33.setScaled(true);
        appearance4.addBasicElement(checkOut33);
        checkOut33.onAttributesInitialized();
        final PixmapElement checkOut34 = PixmapElement.checkOut();
        checkOut34.setElementMap(elementMap);
        checkOut34.setHeight(7);
        checkOut34.setPosition(Alignment17.CENTER);
        checkOut34.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut34.setWidth(1);
        checkOut34.setX(777);
        checkOut34.setY(436);
        checkOut33.addBasicElement(checkOut34);
        checkOut34.onAttributesInitialized();
        checkOut34.onChildrenAdded();
        checkOut33.onChildrenAdded();
        final String id9 = "buttonFlatBorderDisabled";
        final PixmapBorder pixmapBorder4 = new PixmapBorder();
        pixmapBorder4.onCheckOut();
        pixmapBorder4.setElementMap(elementMap);
        if (elementMap != null && id9 != null) {
            elementMap.add(id9, pixmapBorder4);
        }
        appearance4.addBasicElement(pixmapBorder4);
        pixmapBorder4.onAttributesInitialized();
        final PixmapElement checkOut35 = PixmapElement.checkOut();
        checkOut35.setElementMap(elementMap);
        checkOut35.setHeight(3);
        checkOut35.setPosition(Alignment17.NORTH_WEST);
        checkOut35.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut35.setWidth(3);
        checkOut35.setX(111);
        checkOut35.setY(243);
        pixmapBorder4.addBasicElement(checkOut35);
        checkOut35.onAttributesInitialized();
        checkOut35.onChildrenAdded();
        final PixmapElement checkOut36 = PixmapElement.checkOut();
        checkOut36.setElementMap(elementMap);
        checkOut36.setHeight(3);
        checkOut36.setPosition(Alignment17.NORTH);
        checkOut36.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut36.setWidth(1);
        checkOut36.setX(220);
        checkOut36.setY(263);
        pixmapBorder4.addBasicElement(checkOut36);
        checkOut36.onAttributesInitialized();
        checkOut36.onChildrenAdded();
        final PixmapElement checkOut37 = PixmapElement.checkOut();
        checkOut37.setElementMap(elementMap);
        checkOut37.setHeight(3);
        checkOut37.setPosition(Alignment17.NORTH_EAST);
        checkOut37.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut37.setWidth(3);
        checkOut37.setX(968);
        checkOut37.setY(239);
        pixmapBorder4.addBasicElement(checkOut37);
        checkOut37.onAttributesInitialized();
        checkOut37.onChildrenAdded();
        final PixmapElement checkOut38 = PixmapElement.checkOut();
        checkOut38.setElementMap(elementMap);
        checkOut38.setHeight(7);
        checkOut38.setPosition(Alignment17.WEST);
        checkOut38.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut38.setWidth(3);
        checkOut38.setX(88);
        checkOut38.setY(538);
        pixmapBorder4.addBasicElement(checkOut38);
        checkOut38.onAttributesInitialized();
        checkOut38.onChildrenAdded();
        final PixmapElement checkOut39 = PixmapElement.checkOut();
        checkOut39.setElementMap(elementMap);
        checkOut39.setHeight(7);
        checkOut39.setPosition(Alignment17.EAST);
        checkOut39.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut39.setWidth(3);
        checkOut39.setX(88);
        checkOut39.setY(518);
        pixmapBorder4.addBasicElement(checkOut39);
        checkOut39.onAttributesInitialized();
        checkOut39.onChildrenAdded();
        final PixmapElement checkOut40 = PixmapElement.checkOut();
        checkOut40.setElementMap(elementMap);
        checkOut40.setHeight(3);
        checkOut40.setPosition(Alignment17.SOUTH_WEST);
        checkOut40.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut40.setWidth(3);
        checkOut40.setX(111);
        checkOut40.setY(255);
        pixmapBorder4.addBasicElement(checkOut40);
        checkOut40.onAttributesInitialized();
        checkOut40.onChildrenAdded();
        final PixmapElement checkOut41 = PixmapElement.checkOut();
        checkOut41.setElementMap(elementMap);
        checkOut41.setHeight(3);
        checkOut41.setPosition(Alignment17.SOUTH);
        checkOut41.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut41.setWidth(1);
        checkOut41.setX(321);
        checkOut41.setY(248);
        pixmapBorder4.addBasicElement(checkOut41);
        checkOut41.onAttributesInitialized();
        checkOut41.onChildrenAdded();
        this.method0(pixmapBorder4);
        pixmapBorder4.onChildrenAdded();
        appearance4.onChildrenAdded();
    }
    
    public BasicElement method0(final BasicElement basicElement) {
        final ElementMap elementMap = this.elementMaps.peek();
        final PixmapElement checkOut = PixmapElement.checkOut();
        checkOut.setElementMap(elementMap);
        checkOut.setHeight(3);
        checkOut.setPosition(Alignment17.SOUTH_EAST);
        checkOut.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut.setWidth(3);
        checkOut.setX(229);
        checkOut.setY(446);
        basicElement.addBasicElement(checkOut);
        checkOut.onAttributesInitialized();
        checkOut.onChildrenAdded();
        return checkOut;
    }
}
