package com.ankamagames.wakfu.client.ui.theme;

import java.util.*;
import com.ankamagames.xulor2.component.*;
import java.awt.*;
import com.ankamagames.xulor2.core.*;
import com.ankamagames.xulor2.appearance.spacing.*;
import com.ankamagames.xulor2.util.alignment.*;
import com.ankamagames.framework.graphics.engine.geometry.*;
import com.ankamagames.xulor2.decorator.*;
import com.ankamagames.xulor2.appearance.*;

public class Tree2 implements StyleSetter
{
    private DocumentParser doc;
    private Stack<ElementMap> elementMaps;
    
    public Tree2() {
        super();
        this.elementMaps = new Stack<ElementMap>();
    }
    
    @Override
    public void applyStyle(final ElementMap item, final DocumentParser doc, final Widget widget) {
        this.doc = doc;
        this.elementMaps.push(item);
        final ElementMap elementMap = this.elementMaps.peek();
        final DecoratorAppearance appearance = widget.getAppearance();
        appearance.setElementMap(elementMap);
        widget.addBasicElement(appearance);
        appearance.onAttributesInitialized();
        final DecoratorAppearance appearance2 = appearance.getParentOfType(Widget.class).getAppearance();
        appearance2.setElementMap(elementMap);
        appearance2.onAttributesInitialized();
        final Border element = new Border();
        element.onCheckOut();
        element.setElementMap(elementMap);
        element.setInsets(new Insets(6, 7, 6, 7));
        appearance2.addBasicElement(element);
        element.onAttributesInitialized();
        element.onChildrenAdded();
        final String id = "caracContainerBackground";
        final PixmapBackground checkOut = PixmapBackground.checkOut();
        checkOut.setElementMap(elementMap);
        if (elementMap != null && id != null) {
            elementMap.add(id, checkOut);
        }
        checkOut.setScaled(true);
        appearance2.addBasicElement(checkOut);
        checkOut.onAttributesInitialized();
        final PixmapElement checkOut2 = PixmapElement.checkOut();
        checkOut2.setElementMap(elementMap);
        checkOut2.setHeight(6);
        checkOut2.setPosition(Alignment17.NORTH_WEST);
        checkOut2.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut2.setWidth(7);
        checkOut2.setX(530);
        checkOut2.setY(307);
        checkOut.addBasicElement(checkOut2);
        checkOut2.onAttributesInitialized();
        checkOut2.onChildrenAdded();
        final PixmapElement checkOut3 = PixmapElement.checkOut();
        checkOut3.setElementMap(elementMap);
        checkOut3.setHeight(6);
        checkOut3.setPosition(Alignment17.NORTH);
        checkOut3.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut3.setWidth(1);
        checkOut3.setX(1018);
        checkOut3.setY(352);
        checkOut.addBasicElement(checkOut3);
        checkOut3.onAttributesInitialized();
        checkOut3.onChildrenAdded();
        final PixmapElement checkOut4 = PixmapElement.checkOut();
        checkOut4.setElementMap(elementMap);
        checkOut4.setFlipHorizontaly(true);
        checkOut4.setHeight(6);
        checkOut4.setPosition(Alignment17.NORTH_EAST);
        checkOut4.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut4.setWidth(7);
        checkOut4.setX(530);
        checkOut4.setY(307);
        checkOut.addBasicElement(checkOut4);
        checkOut4.onAttributesInitialized();
        checkOut4.onChildrenAdded();
        final PixmapElement checkOut5 = PixmapElement.checkOut();
        checkOut5.setElementMap(elementMap);
        checkOut5.setHeight(1);
        checkOut5.setPosition(Alignment17.WEST);
        checkOut5.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut5.setWidth(7);
        checkOut5.setX(1013);
        checkOut5.setY(162);
        checkOut.addBasicElement(checkOut5);
        checkOut5.onAttributesInitialized();
        checkOut5.onChildrenAdded();
        final PixmapElement checkOut6 = PixmapElement.checkOut();
        checkOut6.setElementMap(elementMap);
        checkOut6.setHeight(1);
        checkOut6.setPosition(Alignment17.CENTER);
        checkOut6.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut6.setWidth(1);
        checkOut6.setX(112);
        checkOut6.setY(191);
        checkOut.addBasicElement(checkOut6);
        checkOut6.onAttributesInitialized();
        checkOut6.onChildrenAdded();
        final PixmapElement checkOut7 = PixmapElement.checkOut();
        checkOut7.setElementMap(elementMap);
        checkOut7.setFlipHorizontaly(true);
        checkOut7.setHeight(1);
        checkOut7.setPosition(Alignment17.EAST);
        checkOut7.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut7.setWidth(7);
        checkOut7.setX(1013);
        checkOut7.setY(162);
        checkOut.addBasicElement(checkOut7);
        checkOut7.onAttributesInitialized();
        checkOut7.onChildrenAdded();
        final PixmapElement checkOut8 = PixmapElement.checkOut();
        checkOut8.setElementMap(elementMap);
        checkOut8.setFlipVerticaly(true);
        checkOut8.setHeight(6);
        checkOut8.setPosition(Alignment17.SOUTH_WEST);
        checkOut8.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut8.setWidth(7);
        checkOut8.setX(530);
        checkOut8.setY(307);
        checkOut.addBasicElement(checkOut8);
        checkOut8.onAttributesInitialized();
        checkOut8.onChildrenAdded();
        final PixmapElement checkOut9 = PixmapElement.checkOut();
        checkOut9.setElementMap(elementMap);
        checkOut9.setFlipVerticaly(true);
        checkOut9.setHeight(6);
        checkOut9.setPosition(Alignment17.SOUTH);
        checkOut9.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut9.setWidth(1);
        checkOut9.setX(1018);
        checkOut9.setY(352);
        checkOut.addBasicElement(checkOut9);
        checkOut9.onAttributesInitialized();
        checkOut9.onChildrenAdded();
        final PixmapElement checkOut10 = PixmapElement.checkOut();
        checkOut10.setElementMap(elementMap);
        checkOut10.setFlipHorizontaly(true);
        checkOut10.setFlipVerticaly(true);
        checkOut10.setHeight(6);
        checkOut10.setPosition(Alignment17.SOUTH_EAST);
        checkOut10.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut10.setWidth(7);
        checkOut10.setX(530);
        checkOut10.setY(307);
        checkOut.addBasicElement(checkOut10);
        checkOut10.onAttributesInitialized();
        checkOut10.onChildrenAdded();
        checkOut.onChildrenAdded();
        appearance2.onChildrenAdded();
        final Widget widgetByThemeElementName = appearance.getParentOfType(Widget.class).getWidgetByThemeElementName("scrollBar", false);
        if (widgetByThemeElementName != null) {
            final DecoratorAppearance appearance3 = widgetByThemeElementName.getAppearance();
            appearance3.setElementMap(elementMap);
            widgetByThemeElementName.addBasicElement(appearance3);
            appearance3.onAttributesInitialized();
            final Widget widgetByThemeElementName2 = appearance3.getParentOfType(Widget.class).getWidgetByThemeElementName("verticalIncreaseButton", false);
            if (widgetByThemeElementName2 != null) {
                final Padding element2 = new Padding();
                element2.onCheckOut();
                element2.setElementMap(elementMap);
                element2.setInsets(new Insets(3, 0, 3, 0));
                widgetByThemeElementName2.addBasicElement(element2);
                element2.onAttributesInitialized();
                element2.onChildrenAdded();
                final DecoratorAppearance appearance4 = widgetByThemeElementName2.getAppearance();
                appearance4.setElementMap(elementMap);
                ((TextWidgetAppearance)appearance4).setAlignment(Alignment9.CENTER);
                appearance4.setState("default");
                widgetByThemeElementName2.addBasicElement(appearance4);
                appearance4.onAttributesInitialized();
                final PixmapElement checkOut11 = PixmapElement.checkOut();
                checkOut11.setElementMap(elementMap);
                checkOut11.setHeight(18);
                checkOut11.setPosition(Alignment17.CENTER);
                checkOut11.setRotation(GeometrySprite.SpriteRotation.QUARTER_CLOCKWISE);
                checkOut11.setTexture(this.doc.getTexture("default_1.tga"));
                checkOut11.setWidth(16);
                checkOut11.setX(215);
                checkOut11.setY(744);
                appearance4.addBasicElement(checkOut11);
                checkOut11.onAttributesInitialized();
                checkOut11.onChildrenAdded();
                appearance4.onChildrenAdded();
                final DecoratorAppearance appearance5 = widgetByThemeElementName2.getAppearance();
                appearance5.setElementMap(elementMap);
                ((TextWidgetAppearance)appearance5).setAlignment(Alignment9.CENTER);
                appearance5.setState("mouseHover");
                widgetByThemeElementName2.addBasicElement(appearance5);
                appearance5.onAttributesInitialized();
                final PixmapElement checkOut12 = PixmapElement.checkOut();
                checkOut12.setElementMap(elementMap);
                checkOut12.setHeight(18);
                checkOut12.setPosition(Alignment17.CENTER);
                checkOut12.setRotation(GeometrySprite.SpriteRotation.QUARTER_CLOCKWISE);
                checkOut12.setTexture(this.doc.getTexture("default_0.tga"));
                checkOut12.setWidth(16);
                checkOut12.setX(964);
                checkOut12.setY(14);
                appearance5.addBasicElement(checkOut12);
                checkOut12.onAttributesInitialized();
                checkOut12.onChildrenAdded();
                appearance5.onChildrenAdded();
                final DecoratorAppearance appearance6 = widgetByThemeElementName2.getAppearance();
                appearance6.setElementMap(elementMap);
                ((TextWidgetAppearance)appearance6).setAlignment(Alignment9.CENTER);
                appearance6.setState("pressed");
                widgetByThemeElementName2.addBasicElement(appearance6);
                appearance6.onAttributesInitialized();
                final PixmapElement checkOut13 = PixmapElement.checkOut();
                checkOut13.setElementMap(elementMap);
                checkOut13.setHeight(18);
                checkOut13.setPosition(Alignment17.CENTER);
                checkOut13.setRotation(GeometrySprite.SpriteRotation.QUARTER_CLOCKWISE);
                checkOut13.setTexture(this.doc.getTexture("default_1.tga"));
                checkOut13.setWidth(16);
                checkOut13.setX(215);
                checkOut13.setY(723);
                appearance6.addBasicElement(checkOut13);
                checkOut13.onAttributesInitialized();
                checkOut13.onChildrenAdded();
                appearance6.onChildrenAdded();
            }
            final Widget widgetByThemeElementName3 = appearance3.getParentOfType(Widget.class).getWidgetByThemeElementName("verticalDecreaseButton", false);
            if (widgetByThemeElementName3 != null) {
                final Padding element3 = new Padding();
                element3.onCheckOut();
                element3.setElementMap(elementMap);
                element3.setInsets(new Insets(3, 0, 3, 0));
                widgetByThemeElementName3.addBasicElement(element3);
                element3.onAttributesInitialized();
                element3.onChildrenAdded();
                final DecoratorAppearance appearance7 = widgetByThemeElementName3.getAppearance();
                appearance7.setElementMap(elementMap);
                ((TextWidgetAppearance)appearance7).setAlignment(Alignment9.CENTER);
                appearance7.setState("default");
                widgetByThemeElementName3.addBasicElement(appearance7);
                appearance7.onAttributesInitialized();
                final PixmapElement checkOut14 = PixmapElement.checkOut();
                checkOut14.setElementMap(elementMap);
                checkOut14.setHeight(18);
                checkOut14.setPosition(Alignment17.CENTER);
                checkOut14.setRotation(GeometrySprite.SpriteRotation.QUARTER_COUNTER_CLOCKWISE);
                checkOut14.setTexture(this.doc.getTexture("default_1.tga"));
                checkOut14.setWidth(16);
                checkOut14.setX(215);
                checkOut14.setY(744);
                appearance7.addBasicElement(checkOut14);
                checkOut14.onAttributesInitialized();
                checkOut14.onChildrenAdded();
                appearance7.onChildrenAdded();
                final DecoratorAppearance appearance8 = widgetByThemeElementName3.getAppearance();
                appearance8.setElementMap(elementMap);
                ((TextWidgetAppearance)appearance8).setAlignment(Alignment9.CENTER);
                appearance8.setState("mouseHover");
                widgetByThemeElementName3.addBasicElement(appearance8);
                appearance8.onAttributesInitialized();
                final PixmapElement checkOut15 = PixmapElement.checkOut();
                checkOut15.setElementMap(elementMap);
                checkOut15.setHeight(18);
                checkOut15.setPosition(Alignment17.CENTER);
                checkOut15.setRotation(GeometrySprite.SpriteRotation.QUARTER_COUNTER_CLOCKWISE);
                checkOut15.setTexture(this.doc.getTexture("default_0.tga"));
                checkOut15.setWidth(16);
                checkOut15.setX(964);
                checkOut15.setY(14);
                appearance8.addBasicElement(checkOut15);
                checkOut15.onAttributesInitialized();
                checkOut15.onChildrenAdded();
                appearance8.onChildrenAdded();
                final DecoratorAppearance appearance9 = widgetByThemeElementName3.getAppearance();
                appearance9.setElementMap(elementMap);
                ((TextWidgetAppearance)appearance9).setAlignment(Alignment9.CENTER);
                appearance9.setState("pressed");
                widgetByThemeElementName3.addBasicElement(appearance9);
                appearance9.onAttributesInitialized();
                final PixmapElement checkOut16 = PixmapElement.checkOut();
                checkOut16.setElementMap(elementMap);
                checkOut16.setHeight(18);
                checkOut16.setPosition(Alignment17.CENTER);
                checkOut16.setRotation(GeometrySprite.SpriteRotation.QUARTER_COUNTER_CLOCKWISE);
                checkOut16.setTexture(this.doc.getTexture("default_1.tga"));
                checkOut16.setWidth(16);
                checkOut16.setX(215);
                checkOut16.setY(723);
                appearance9.addBasicElement(checkOut16);
                checkOut16.onAttributesInitialized();
                checkOut16.onChildrenAdded();
                appearance9.onChildrenAdded();
            }
            final Widget widgetByThemeElementName4 = appearance3.getParentOfType(Widget.class).getWidgetByThemeElementName("verticalSlider", false);
            if (widgetByThemeElementName4 != null) {
                final DecoratorAppearance appearance10 = widgetByThemeElementName4.getAppearance();
                appearance10.setElementMap(elementMap);
                widgetByThemeElementName4.addBasicElement(appearance10);
                appearance10.onAttributesInitialized();
                final Padding element4 = new Padding();
                element4.onCheckOut();
                element4.setElementMap(elementMap);
                element4.setInsets(new Insets(0, 4, 0, 4));
                appearance10.addBasicElement(element4);
                element4.onAttributesInitialized();
                element4.onChildrenAdded();
                final Widget widgetByThemeElementName5 = appearance10.getParentOfType(Widget.class).getWidgetByThemeElementName("verticalButton", false);
                if (widgetByThemeElementName5 != null) {
                    final DecoratorAppearance appearance11 = widgetByThemeElementName5.getAppearance();
                    appearance11.setElementMap(elementMap);
                    appearance11.setState("default");
                    widgetByThemeElementName5.addBasicElement(appearance11);
                    appearance11.onAttributesInitialized();
                    final PixmapBorder element5 = new PixmapBorder();
                    element5.onCheckOut();
                    element5.setElementMap(elementMap);
                    appearance11.addBasicElement(element5);
                    element5.onAttributesInitialized();
                    final PixmapElement checkOut17 = PixmapElement.checkOut();
                    checkOut17.setElementMap(elementMap);
                    checkOut17.setHeight(4);
                    checkOut17.setPosition(Alignment17.NORTH_WEST);
                    checkOut17.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut17.setWidth(1);
                    checkOut17.setX(540);
                    checkOut17.setY(286);
                    element5.addBasicElement(checkOut17);
                    checkOut17.onAttributesInitialized();
                    checkOut17.onChildrenAdded();
                    final PixmapElement checkOut18 = PixmapElement.checkOut();
                    checkOut18.setElementMap(elementMap);
                    checkOut18.setHeight(4);
                    checkOut18.setPosition(Alignment17.NORTH);
                    checkOut18.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut18.setWidth(11);
                    checkOut18.setX(146);
                    checkOut18.setY(239);
                    element5.addBasicElement(checkOut18);
                    checkOut18.onAttributesInitialized();
                    checkOut18.onChildrenAdded();
                    final PixmapElement checkOut19 = PixmapElement.checkOut();
                    checkOut19.setElementMap(elementMap);
                    checkOut19.setHeight(4);
                    checkOut19.setPosition(Alignment17.NORTH_EAST);
                    checkOut19.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut19.setWidth(1);
                    checkOut19.setX(594);
                    checkOut19.setY(286);
                    element5.addBasicElement(checkOut19);
                    checkOut19.onAttributesInitialized();
                    checkOut19.onChildrenAdded();
                    final PixmapElement checkOut20 = PixmapElement.checkOut();
                    checkOut20.setElementMap(elementMap);
                    checkOut20.setHeight(13);
                    checkOut20.setPosition(Alignment17.EAST);
                    checkOut20.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut20.setWidth(1);
                    checkOut20.setX(827);
                    checkOut20.setY(753);
                    element5.addBasicElement(checkOut20);
                    checkOut20.onAttributesInitialized();
                    checkOut20.onChildrenAdded();
                    final PixmapElement checkOut21 = PixmapElement.checkOut();
                    checkOut21.setElementMap(elementMap);
                    checkOut21.setHeight(4);
                    checkOut21.setPosition(Alignment17.SOUTH_EAST);
                    checkOut21.setTexture(this.doc.getTexture("default_0.tga"));
                    checkOut21.setWidth(1);
                    checkOut21.setX(315);
                    checkOut21.setY(474);
                    element5.addBasicElement(checkOut21);
                    checkOut21.onAttributesInitialized();
                    checkOut21.onChildrenAdded();
                    final PixmapElement checkOut22 = PixmapElement.checkOut();
                    checkOut22.setElementMap(elementMap);
                    checkOut22.setHeight(4);
                    checkOut22.setPosition(Alignment17.SOUTH);
                    checkOut22.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut22.setWidth(11);
                    checkOut22.setX(282);
                    checkOut22.setY(283);
                    element5.addBasicElement(checkOut22);
                    checkOut22.onAttributesInitialized();
                    checkOut22.onChildrenAdded();
                    final PixmapElement checkOut23 = PixmapElement.checkOut();
                    checkOut23.setElementMap(elementMap);
                    checkOut23.setHeight(4);
                    checkOut23.setPosition(Alignment17.SOUTH_WEST);
                    checkOut23.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut23.setWidth(1);
                    checkOut23.setX(594);
                    checkOut23.setY(286);
                    element5.addBasicElement(checkOut23);
                    checkOut23.onAttributesInitialized();
                    checkOut23.onChildrenAdded();
                    final PixmapElement checkOut24 = PixmapElement.checkOut();
                    checkOut24.setElementMap(elementMap);
                    checkOut24.setHeight(13);
                    checkOut24.setPosition(Alignment17.WEST);
                    checkOut24.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut24.setWidth(1);
                    checkOut24.setX(827);
                    checkOut24.setY(753);
                    element5.addBasicElement(checkOut24);
                    checkOut24.onAttributesInitialized();
                    checkOut24.onChildrenAdded();
                    element5.onChildrenAdded();
                    final PixmapBackground checkOut25 = PixmapBackground.checkOut();
                    checkOut25.setElementMap(elementMap);
                    checkOut25.setEnabled(true);
                    checkOut25.setScaled(true);
                    appearance11.addBasicElement(checkOut25);
                    checkOut25.onAttributesInitialized();
                    final PixmapElement checkOut26 = PixmapElement.checkOut();
                    checkOut26.setElementMap(elementMap);
                    checkOut26.setHeight(2);
                    checkOut26.setPosition(Alignment17.CENTER);
                    checkOut26.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut26.setWidth(11);
                    checkOut26.setX(829);
                    checkOut26.setY(283);
                    checkOut25.addBasicElement(checkOut26);
                    checkOut26.onAttributesInitialized();
                    checkOut26.onChildrenAdded();
                    checkOut25.onChildrenAdded();
                    final PixmapElement checkOut27 = PixmapElement.checkOut();
                    checkOut27.setElementMap(elementMap);
                    checkOut27.setHeight(5);
                    checkOut27.setPosition(Alignment17.CENTER);
                    checkOut27.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut27.setWidth(11);
                    checkOut27.setX(594);
                    checkOut27.setY(669);
                    appearance11.addBasicElement(checkOut27);
                    checkOut27.onAttributesInitialized();
                    checkOut27.onChildrenAdded();
                    appearance11.onChildrenAdded();
                    final DecoratorAppearance appearance12 = widgetByThemeElementName5.getAppearance();
                    appearance12.setElementMap(elementMap);
                    appearance12.setState("mouseHover");
                    widgetByThemeElementName5.addBasicElement(appearance12);
                    appearance12.onAttributesInitialized();
                    final PixmapBorder element6 = new PixmapBorder();
                    element6.onCheckOut();
                    element6.setElementMap(elementMap);
                    element6.setEnabled(false);
                    appearance12.addBasicElement(element6);
                    element6.onAttributesInitialized();
                    final PixmapElement checkOut28 = PixmapElement.checkOut();
                    checkOut28.setElementMap(elementMap);
                    checkOut28.setHeight(4);
                    checkOut28.setPosition(Alignment17.NORTH_WEST);
                    checkOut28.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut28.setWidth(1);
                    checkOut28.setX(321);
                    checkOut28.setY(278);
                    element6.addBasicElement(checkOut28);
                    checkOut28.onAttributesInitialized();
                    checkOut28.onChildrenAdded();
                    final PixmapElement checkOut29 = PixmapElement.checkOut();
                    checkOut29.setElementMap(elementMap);
                    checkOut29.setHeight(4);
                    checkOut29.setPosition(Alignment17.NORTH);
                    checkOut29.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut29.setWidth(11);
                    checkOut29.setX(185);
                    checkOut29.setY(283);
                    element6.addBasicElement(checkOut29);
                    checkOut29.onAttributesInitialized();
                    checkOut29.onChildrenAdded();
                    final PixmapElement checkOut30 = PixmapElement.checkOut();
                    checkOut30.setElementMap(elementMap);
                    checkOut30.setHeight(4);
                    checkOut30.setPosition(Alignment17.NORTH_EAST);
                    checkOut30.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut30.setWidth(1);
                    checkOut30.setX(594);
                    checkOut30.setY(286);
                    element6.addBasicElement(checkOut30);
                    checkOut30.onAttributesInitialized();
                    checkOut30.onChildrenAdded();
                    final PixmapElement checkOut31 = PixmapElement.checkOut();
                    checkOut31.setElementMap(elementMap);
                    checkOut31.setHeight(13);
                    checkOut31.setPosition(Alignment17.EAST);
                    checkOut31.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut31.setWidth(1);
                    checkOut31.setX(397);
                    checkOut31.setY(718);
                    element6.addBasicElement(checkOut31);
                    checkOut31.onAttributesInitialized();
                    checkOut31.onChildrenAdded();
                    final PixmapElement checkOut32 = PixmapElement.checkOut();
                    checkOut32.setElementMap(elementMap);
                    checkOut32.setHeight(4);
                    checkOut32.setPosition(Alignment17.SOUTH_EAST);
                    checkOut32.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut32.setWidth(1);
                    checkOut32.setX(294);
                    checkOut32.setY(330);
                    element6.addBasicElement(checkOut32);
                    checkOut32.onAttributesInitialized();
                    checkOut32.onChildrenAdded();
                    final PixmapElement checkOut33 = PixmapElement.checkOut();
                    checkOut33.setElementMap(elementMap);
                    checkOut33.setHeight(4);
                    checkOut33.setPosition(Alignment17.SOUTH);
                    checkOut33.setTexture(this.doc.getTexture("default_1.tga"));
                    checkOut33.setWidth(11);
                    checkOut33.setX(595);
                    checkOut33.setY(586);
                    element6.addBasicElement(checkOut33);
                    checkOut33.onAttributesInitialized();
                    checkOut33.onChildrenAdded();
                    this.method0(element6);
                    this.method1(element6);
                    element6.onChildrenAdded();
                    this.method2(appearance12);
                    this.method3(appearance12);
                    appearance12.onChildrenAdded();
                    this.method4(widgetByThemeElementName5);
                }
                appearance10.onChildrenAdded();
            }
            appearance3.onChildrenAdded();
        }
        appearance.onChildrenAdded();
    }
    
    public BasicElement method0(final BasicElement basicElement) {
        final ElementMap elementMap = this.elementMaps.peek();
        final PixmapElement checkOut = PixmapElement.checkOut();
        checkOut.setElementMap(elementMap);
        checkOut.setHeight(4);
        checkOut.setPosition(Alignment17.SOUTH_WEST);
        checkOut.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut.setWidth(1);
        checkOut.setX(594);
        checkOut.setY(286);
        basicElement.addBasicElement(checkOut);
        checkOut.onAttributesInitialized();
        checkOut.onChildrenAdded();
        return checkOut;
    }
    
    public BasicElement method1(final BasicElement basicElement) {
        final ElementMap elementMap = this.elementMaps.peek();
        final PixmapElement checkOut = PixmapElement.checkOut();
        checkOut.setElementMap(elementMap);
        checkOut.setHeight(13);
        checkOut.setPosition(Alignment17.WEST);
        checkOut.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut.setWidth(1);
        checkOut.setX(397);
        checkOut.setY(718);
        basicElement.addBasicElement(checkOut);
        checkOut.onAttributesInitialized();
        checkOut.onChildrenAdded();
        return checkOut;
    }
    
    public BasicElement method2(final BasicElement basicElement) {
        final ElementMap elementMap = this.elementMaps.peek();
        final PixmapBackground checkOut = PixmapBackground.checkOut();
        checkOut.setElementMap(elementMap);
        checkOut.setEnabled(false);
        checkOut.setScaled(true);
        basicElement.addBasicElement(checkOut);
        checkOut.onAttributesInitialized();
        final PixmapElement checkOut2 = PixmapElement.checkOut();
        checkOut2.setElementMap(elementMap);
        checkOut2.setHeight(2);
        checkOut2.setPosition(Alignment17.CENTER);
        checkOut2.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut2.setWidth(11);
        checkOut2.setX(800);
        checkOut2.setY(199);
        checkOut.addBasicElement(checkOut2);
        checkOut2.onAttributesInitialized();
        checkOut2.onChildrenAdded();
        checkOut.onChildrenAdded();
        return checkOut;
    }
    
    public BasicElement method3(final BasicElement basicElement) {
        final ElementMap elementMap = this.elementMaps.peek();
        final PixmapElement checkOut = PixmapElement.checkOut();
        checkOut.setElementMap(elementMap);
        checkOut.setHeight(5);
        checkOut.setPosition(Alignment17.CENTER);
        checkOut.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut.setWidth(11);
        checkOut.setX(968);
        checkOut.setY(330);
        basicElement.addBasicElement(checkOut);
        checkOut.onAttributesInitialized();
        checkOut.onChildrenAdded();
        return checkOut;
    }
    
    public BasicElement method4(final BasicElement basicElement) {
        final ElementMap elementMap = this.elementMaps.peek();
        final DecoratorAppearance appearance = ((Widget)basicElement).getAppearance();
        appearance.setElementMap(elementMap);
        appearance.setState("pressed");
        basicElement.addBasicElement(appearance);
        appearance.onAttributesInitialized();
        final PixmapBorder element = new PixmapBorder();
        element.onCheckOut();
        element.setElementMap(elementMap);
        element.setEnabled(false);
        appearance.addBasicElement(element);
        element.onAttributesInitialized();
        final PixmapElement checkOut = PixmapElement.checkOut();
        checkOut.setElementMap(elementMap);
        checkOut.setHeight(4);
        checkOut.setPosition(Alignment17.NORTH_WEST);
        checkOut.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut.setWidth(1);
        checkOut.setX(255);
        checkOut.setY(292);
        element.addBasicElement(checkOut);
        checkOut.onAttributesInitialized();
        checkOut.onChildrenAdded();
        final PixmapElement checkOut2 = PixmapElement.checkOut();
        checkOut2.setElementMap(elementMap);
        checkOut2.setHeight(4);
        checkOut2.setPosition(Alignment17.NORTH);
        checkOut2.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut2.setWidth(11);
        checkOut2.setX(280);
        checkOut2.setY(330);
        element.addBasicElement(checkOut2);
        checkOut2.onAttributesInitialized();
        checkOut2.onChildrenAdded();
        final PixmapElement checkOut3 = PixmapElement.checkOut();
        checkOut3.setElementMap(elementMap);
        checkOut3.setHeight(4);
        checkOut3.setPosition(Alignment17.NORTH_EAST);
        checkOut3.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut3.setWidth(1);
        checkOut3.setX(594);
        checkOut3.setY(286);
        element.addBasicElement(checkOut3);
        checkOut3.onAttributesInitialized();
        checkOut3.onChildrenAdded();
        final PixmapElement checkOut4 = PixmapElement.checkOut();
        checkOut4.setElementMap(elementMap);
        checkOut4.setHeight(13);
        checkOut4.setPosition(Alignment17.EAST);
        checkOut4.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut4.setWidth(1);
        checkOut4.setX(397);
        checkOut4.setY(766);
        element.addBasicElement(checkOut4);
        checkOut4.onAttributesInitialized();
        checkOut4.onChildrenAdded();
        final PixmapElement checkOut5 = PixmapElement.checkOut();
        checkOut5.setElementMap(elementMap);
        checkOut5.setHeight(4);
        checkOut5.setPosition(Alignment17.SOUTH_EAST);
        checkOut5.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut5.setWidth(1);
        checkOut5.setX(628);
        checkOut5.setY(276);
        element.addBasicElement(checkOut5);
        checkOut5.onAttributesInitialized();
        checkOut5.onChildrenAdded();
        final PixmapElement checkOut6 = PixmapElement.checkOut();
        checkOut6.setElementMap(elementMap);
        checkOut6.setHeight(4);
        checkOut6.setPosition(Alignment17.SOUTH);
        checkOut6.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut6.setWidth(11);
        checkOut6.setX(920);
        checkOut6.setY(587);
        element.addBasicElement(checkOut6);
        checkOut6.onAttributesInitialized();
        checkOut6.onChildrenAdded();
        final PixmapElement checkOut7 = PixmapElement.checkOut();
        checkOut7.setElementMap(elementMap);
        checkOut7.setHeight(4);
        checkOut7.setPosition(Alignment17.SOUTH_WEST);
        checkOut7.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut7.setWidth(1);
        checkOut7.setX(594);
        checkOut7.setY(286);
        element.addBasicElement(checkOut7);
        checkOut7.onAttributesInitialized();
        checkOut7.onChildrenAdded();
        final PixmapElement checkOut8 = PixmapElement.checkOut();
        checkOut8.setElementMap(elementMap);
        checkOut8.setHeight(13);
        checkOut8.setPosition(Alignment17.WEST);
        checkOut8.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut8.setWidth(1);
        checkOut8.setX(397);
        checkOut8.setY(766);
        element.addBasicElement(checkOut8);
        checkOut8.onAttributesInitialized();
        checkOut8.onChildrenAdded();
        element.onChildrenAdded();
        final PixmapBackground checkOut9 = PixmapBackground.checkOut();
        checkOut9.setElementMap(elementMap);
        checkOut9.setEnabled(false);
        checkOut9.setScaled(true);
        appearance.addBasicElement(checkOut9);
        checkOut9.onAttributesInitialized();
        final PixmapElement checkOut10 = PixmapElement.checkOut();
        checkOut10.setElementMap(elementMap);
        checkOut10.setHeight(2);
        checkOut10.setPosition(Alignment17.CENTER);
        checkOut10.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut10.setWidth(11);
        checkOut10.setX(379);
        checkOut10.setY(239);
        checkOut9.addBasicElement(checkOut10);
        checkOut10.onAttributesInitialized();
        checkOut10.onChildrenAdded();
        checkOut9.onChildrenAdded();
        final PixmapElement checkOut11 = PixmapElement.checkOut();
        checkOut11.setElementMap(elementMap);
        checkOut11.setHeight(5);
        checkOut11.setPosition(Alignment17.CENTER);
        checkOut11.setTexture(this.doc.getTexture("default_1.tga"));
        checkOut11.setWidth(11);
        checkOut11.setX(361);
        checkOut11.setY(549);
        appearance.addBasicElement(checkOut11);
        checkOut11.onAttributesInitialized();
        checkOut11.onChildrenAdded();
        appearance.onChildrenAdded();
        return appearance;
    }
}
